// Code generated by ent, DO NOT EDIT.

package certificate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-signing/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContainsFold(FieldID, id))
}

// CreateBy applies equality check predicate on the "create_by" field. It's identical to CreateByEQ.
func CreateBy(v uint32) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldCreateBy, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldUpdateTime, v))
}

// DeleteTime applies equality check predicate on the "delete_time" field. It's identical to DeleteTimeEQ.
func DeleteTime(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldDeleteTime, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldTenantID, v))
}

// SubjectCn applies equality check predicate on the "subject_cn" field. It's identical to SubjectCnEQ.
func SubjectCn(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldSubjectCn, v))
}

// SubjectOrg applies equality check predicate on the "subject_org" field. It's identical to SubjectOrgEQ.
func SubjectOrg(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldSubjectOrg, v))
}

// SerialNumber applies equality check predicate on the "serial_number" field. It's identical to SerialNumberEQ.
func SerialNumber(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldSerialNumber, v))
}

// NotBefore applies equality check predicate on the "not_before" field. It's identical to NotBeforeEQ.
func NotBefore(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldNotBefore, v))
}

// NotAfter applies equality check predicate on the "not_after" field. It's identical to NotAfterEQ.
func NotAfter(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldNotAfter, v))
}

// IsCa applies equality check predicate on the "is_ca" field. It's identical to IsCaEQ.
func IsCa(v bool) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldIsCa, v))
}

// ParentID applies equality check predicate on the "parent_id" field. It's identical to ParentIDEQ.
func ParentID(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldParentID, v))
}

// KeyPemEncrypted applies equality check predicate on the "key_pem_encrypted" field. It's identical to KeyPemEncryptedEQ.
func KeyPemEncrypted(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldKeyPemEncrypted, v))
}

// CertPem applies equality check predicate on the "cert_pem" field. It's identical to CertPemEQ.
func CertPem(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldCertPem, v))
}

// CrlPem applies equality check predicate on the "crl_pem" field. It's identical to CrlPemEQ.
func CrlPem(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldCrlPem, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldRevokedAt, v))
}

// RevocationReason applies equality check predicate on the "revocation_reason" field. It's identical to RevocationReasonEQ.
func RevocationReason(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldRevocationReason, v))
}

// CreateByEQ applies the EQ predicate on the "create_by" field.
func CreateByEQ(v uint32) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldCreateBy, v))
}

// CreateByNEQ applies the NEQ predicate on the "create_by" field.
func CreateByNEQ(v uint32) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldCreateBy, v))
}

// CreateByIn applies the In predicate on the "create_by" field.
func CreateByIn(vs ...uint32) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldCreateBy, vs...))
}

// CreateByNotIn applies the NotIn predicate on the "create_by" field.
func CreateByNotIn(vs ...uint32) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldCreateBy, vs...))
}

// CreateByGT applies the GT predicate on the "create_by" field.
func CreateByGT(v uint32) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldCreateBy, v))
}

// CreateByGTE applies the GTE predicate on the "create_by" field.
func CreateByGTE(v uint32) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldCreateBy, v))
}

// CreateByLT applies the LT predicate on the "create_by" field.
func CreateByLT(v uint32) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldCreateBy, v))
}

// CreateByLTE applies the LTE predicate on the "create_by" field.
func CreateByLTE(v uint32) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldCreateBy, v))
}

// CreateByIsNil applies the IsNil predicate on the "create_by" field.
func CreateByIsNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldIsNull(FieldCreateBy))
}

// CreateByNotNil applies the NotNil predicate on the "create_by" field.
func CreateByNotNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldNotNull(FieldCreateBy))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldCreateTime, v))
}

// CreateTimeIsNil applies the IsNil predicate on the "create_time" field.
func CreateTimeIsNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldIsNull(FieldCreateTime))
}

// CreateTimeNotNil applies the NotNil predicate on the "create_time" field.
func CreateTimeNotNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldNotNull(FieldCreateTime))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldUpdateTime, v))
}

// UpdateTimeIsNil applies the IsNil predicate on the "update_time" field.
func UpdateTimeIsNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldIsNull(FieldUpdateTime))
}

// UpdateTimeNotNil applies the NotNil predicate on the "update_time" field.
func UpdateTimeNotNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldNotNull(FieldUpdateTime))
}

// DeleteTimeEQ applies the EQ predicate on the "delete_time" field.
func DeleteTimeEQ(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldDeleteTime, v))
}

// DeleteTimeNEQ applies the NEQ predicate on the "delete_time" field.
func DeleteTimeNEQ(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldDeleteTime, v))
}

// DeleteTimeIn applies the In predicate on the "delete_time" field.
func DeleteTimeIn(vs ...time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldDeleteTime, vs...))
}

// DeleteTimeNotIn applies the NotIn predicate on the "delete_time" field.
func DeleteTimeNotIn(vs ...time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldDeleteTime, vs...))
}

// DeleteTimeGT applies the GT predicate on the "delete_time" field.
func DeleteTimeGT(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldDeleteTime, v))
}

// DeleteTimeGTE applies the GTE predicate on the "delete_time" field.
func DeleteTimeGTE(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldDeleteTime, v))
}

// DeleteTimeLT applies the LT predicate on the "delete_time" field.
func DeleteTimeLT(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldDeleteTime, v))
}

// DeleteTimeLTE applies the LTE predicate on the "delete_time" field.
func DeleteTimeLTE(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldDeleteTime, v))
}

// DeleteTimeIsNil applies the IsNil predicate on the "delete_time" field.
func DeleteTimeIsNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldIsNull(FieldDeleteTime))
}

// DeleteTimeNotNil applies the NotNil predicate on the "delete_time" field.
func DeleteTimeNotNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldNotNull(FieldDeleteTime))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldNotNull(FieldTenantID))
}

// SubjectCnEQ applies the EQ predicate on the "subject_cn" field.
func SubjectCnEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldSubjectCn, v))
}

// SubjectCnNEQ applies the NEQ predicate on the "subject_cn" field.
func SubjectCnNEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldSubjectCn, v))
}

// SubjectCnIn applies the In predicate on the "subject_cn" field.
func SubjectCnIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldSubjectCn, vs...))
}

// SubjectCnNotIn applies the NotIn predicate on the "subject_cn" field.
func SubjectCnNotIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldSubjectCn, vs...))
}

// SubjectCnGT applies the GT predicate on the "subject_cn" field.
func SubjectCnGT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldSubjectCn, v))
}

// SubjectCnGTE applies the GTE predicate on the "subject_cn" field.
func SubjectCnGTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldSubjectCn, v))
}

// SubjectCnLT applies the LT predicate on the "subject_cn" field.
func SubjectCnLT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldSubjectCn, v))
}

// SubjectCnLTE applies the LTE predicate on the "subject_cn" field.
func SubjectCnLTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldSubjectCn, v))
}

// SubjectCnContains applies the Contains predicate on the "subject_cn" field.
func SubjectCnContains(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContains(FieldSubjectCn, v))
}

// SubjectCnHasPrefix applies the HasPrefix predicate on the "subject_cn" field.
func SubjectCnHasPrefix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasPrefix(FieldSubjectCn, v))
}

// SubjectCnHasSuffix applies the HasSuffix predicate on the "subject_cn" field.
func SubjectCnHasSuffix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasSuffix(FieldSubjectCn, v))
}

// SubjectCnEqualFold applies the EqualFold predicate on the "subject_cn" field.
func SubjectCnEqualFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEqualFold(FieldSubjectCn, v))
}

// SubjectCnContainsFold applies the ContainsFold predicate on the "subject_cn" field.
func SubjectCnContainsFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContainsFold(FieldSubjectCn, v))
}

// SubjectOrgEQ applies the EQ predicate on the "subject_org" field.
func SubjectOrgEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldSubjectOrg, v))
}

// SubjectOrgNEQ applies the NEQ predicate on the "subject_org" field.
func SubjectOrgNEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldSubjectOrg, v))
}

// SubjectOrgIn applies the In predicate on the "subject_org" field.
func SubjectOrgIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldSubjectOrg, vs...))
}

// SubjectOrgNotIn applies the NotIn predicate on the "subject_org" field.
func SubjectOrgNotIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldSubjectOrg, vs...))
}

// SubjectOrgGT applies the GT predicate on the "subject_org" field.
func SubjectOrgGT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldSubjectOrg, v))
}

// SubjectOrgGTE applies the GTE predicate on the "subject_org" field.
func SubjectOrgGTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldSubjectOrg, v))
}

// SubjectOrgLT applies the LT predicate on the "subject_org" field.
func SubjectOrgLT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldSubjectOrg, v))
}

// SubjectOrgLTE applies the LTE predicate on the "subject_org" field.
func SubjectOrgLTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldSubjectOrg, v))
}

// SubjectOrgContains applies the Contains predicate on the "subject_org" field.
func SubjectOrgContains(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContains(FieldSubjectOrg, v))
}

// SubjectOrgHasPrefix applies the HasPrefix predicate on the "subject_org" field.
func SubjectOrgHasPrefix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasPrefix(FieldSubjectOrg, v))
}

// SubjectOrgHasSuffix applies the HasSuffix predicate on the "subject_org" field.
func SubjectOrgHasSuffix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasSuffix(FieldSubjectOrg, v))
}

// SubjectOrgIsNil applies the IsNil predicate on the "subject_org" field.
func SubjectOrgIsNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldIsNull(FieldSubjectOrg))
}

// SubjectOrgNotNil applies the NotNil predicate on the "subject_org" field.
func SubjectOrgNotNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldNotNull(FieldSubjectOrg))
}

// SubjectOrgEqualFold applies the EqualFold predicate on the "subject_org" field.
func SubjectOrgEqualFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEqualFold(FieldSubjectOrg, v))
}

// SubjectOrgContainsFold applies the ContainsFold predicate on the "subject_org" field.
func SubjectOrgContainsFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContainsFold(FieldSubjectOrg, v))
}

// SerialNumberEQ applies the EQ predicate on the "serial_number" field.
func SerialNumberEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldSerialNumber, v))
}

// SerialNumberNEQ applies the NEQ predicate on the "serial_number" field.
func SerialNumberNEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldSerialNumber, v))
}

// SerialNumberIn applies the In predicate on the "serial_number" field.
func SerialNumberIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldSerialNumber, vs...))
}

// SerialNumberNotIn applies the NotIn predicate on the "serial_number" field.
func SerialNumberNotIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldSerialNumber, vs...))
}

// SerialNumberGT applies the GT predicate on the "serial_number" field.
func SerialNumberGT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldSerialNumber, v))
}

// SerialNumberGTE applies the GTE predicate on the "serial_number" field.
func SerialNumberGTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldSerialNumber, v))
}

// SerialNumberLT applies the LT predicate on the "serial_number" field.
func SerialNumberLT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldSerialNumber, v))
}

// SerialNumberLTE applies the LTE predicate on the "serial_number" field.
func SerialNumberLTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldSerialNumber, v))
}

// SerialNumberContains applies the Contains predicate on the "serial_number" field.
func SerialNumberContains(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContains(FieldSerialNumber, v))
}

// SerialNumberHasPrefix applies the HasPrefix predicate on the "serial_number" field.
func SerialNumberHasPrefix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasPrefix(FieldSerialNumber, v))
}

// SerialNumberHasSuffix applies the HasSuffix predicate on the "serial_number" field.
func SerialNumberHasSuffix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasSuffix(FieldSerialNumber, v))
}

// SerialNumberEqualFold applies the EqualFold predicate on the "serial_number" field.
func SerialNumberEqualFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEqualFold(FieldSerialNumber, v))
}

// SerialNumberContainsFold applies the ContainsFold predicate on the "serial_number" field.
func SerialNumberContainsFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContainsFold(FieldSerialNumber, v))
}

// NotBeforeEQ applies the EQ predicate on the "not_before" field.
func NotBeforeEQ(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldNotBefore, v))
}

// NotBeforeNEQ applies the NEQ predicate on the "not_before" field.
func NotBeforeNEQ(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldNotBefore, v))
}

// NotBeforeIn applies the In predicate on the "not_before" field.
func NotBeforeIn(vs ...time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldNotBefore, vs...))
}

// NotBeforeNotIn applies the NotIn predicate on the "not_before" field.
func NotBeforeNotIn(vs ...time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldNotBefore, vs...))
}

// NotBeforeGT applies the GT predicate on the "not_before" field.
func NotBeforeGT(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldNotBefore, v))
}

// NotBeforeGTE applies the GTE predicate on the "not_before" field.
func NotBeforeGTE(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldNotBefore, v))
}

// NotBeforeLT applies the LT predicate on the "not_before" field.
func NotBeforeLT(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldNotBefore, v))
}

// NotBeforeLTE applies the LTE predicate on the "not_before" field.
func NotBeforeLTE(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldNotBefore, v))
}

// NotAfterEQ applies the EQ predicate on the "not_after" field.
func NotAfterEQ(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldNotAfter, v))
}

// NotAfterNEQ applies the NEQ predicate on the "not_after" field.
func NotAfterNEQ(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldNotAfter, v))
}

// NotAfterIn applies the In predicate on the "not_after" field.
func NotAfterIn(vs ...time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldNotAfter, vs...))
}

// NotAfterNotIn applies the NotIn predicate on the "not_after" field.
func NotAfterNotIn(vs ...time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldNotAfter, vs...))
}

// NotAfterGT applies the GT predicate on the "not_after" field.
func NotAfterGT(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldNotAfter, v))
}

// NotAfterGTE applies the GTE predicate on the "not_after" field.
func NotAfterGTE(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldNotAfter, v))
}

// NotAfterLT applies the LT predicate on the "not_after" field.
func NotAfterLT(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldNotAfter, v))
}

// NotAfterLTE applies the LTE predicate on the "not_after" field.
func NotAfterLTE(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldNotAfter, v))
}

// IsCaEQ applies the EQ predicate on the "is_ca" field.
func IsCaEQ(v bool) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldIsCa, v))
}

// IsCaNEQ applies the NEQ predicate on the "is_ca" field.
func IsCaNEQ(v bool) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldIsCa, v))
}

// ParentIDEQ applies the EQ predicate on the "parent_id" field.
func ParentIDEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldParentID, v))
}

// ParentIDNEQ applies the NEQ predicate on the "parent_id" field.
func ParentIDNEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldParentID, v))
}

// ParentIDIn applies the In predicate on the "parent_id" field.
func ParentIDIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldParentID, vs...))
}

// ParentIDNotIn applies the NotIn predicate on the "parent_id" field.
func ParentIDNotIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldParentID, vs...))
}

// ParentIDGT applies the GT predicate on the "parent_id" field.
func ParentIDGT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldParentID, v))
}

// ParentIDGTE applies the GTE predicate on the "parent_id" field.
func ParentIDGTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldParentID, v))
}

// ParentIDLT applies the LT predicate on the "parent_id" field.
func ParentIDLT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldParentID, v))
}

// ParentIDLTE applies the LTE predicate on the "parent_id" field.
func ParentIDLTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldParentID, v))
}

// ParentIDContains applies the Contains predicate on the "parent_id" field.
func ParentIDContains(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContains(FieldParentID, v))
}

// ParentIDHasPrefix applies the HasPrefix predicate on the "parent_id" field.
func ParentIDHasPrefix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasPrefix(FieldParentID, v))
}

// ParentIDHasSuffix applies the HasSuffix predicate on the "parent_id" field.
func ParentIDHasSuffix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasSuffix(FieldParentID, v))
}

// ParentIDIsNil applies the IsNil predicate on the "parent_id" field.
func ParentIDIsNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldIsNull(FieldParentID))
}

// ParentIDNotNil applies the NotNil predicate on the "parent_id" field.
func ParentIDNotNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldNotNull(FieldParentID))
}

// ParentIDEqualFold applies the EqualFold predicate on the "parent_id" field.
func ParentIDEqualFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEqualFold(FieldParentID, v))
}

// ParentIDContainsFold applies the ContainsFold predicate on the "parent_id" field.
func ParentIDContainsFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContainsFold(FieldParentID, v))
}

// KeyPemEncryptedEQ applies the EQ predicate on the "key_pem_encrypted" field.
func KeyPemEncryptedEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldKeyPemEncrypted, v))
}

// KeyPemEncryptedNEQ applies the NEQ predicate on the "key_pem_encrypted" field.
func KeyPemEncryptedNEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldKeyPemEncrypted, v))
}

// KeyPemEncryptedIn applies the In predicate on the "key_pem_encrypted" field.
func KeyPemEncryptedIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldKeyPemEncrypted, vs...))
}

// KeyPemEncryptedNotIn applies the NotIn predicate on the "key_pem_encrypted" field.
func KeyPemEncryptedNotIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldKeyPemEncrypted, vs...))
}

// KeyPemEncryptedGT applies the GT predicate on the "key_pem_encrypted" field.
func KeyPemEncryptedGT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldKeyPemEncrypted, v))
}

// KeyPemEncryptedGTE applies the GTE predicate on the "key_pem_encrypted" field.
func KeyPemEncryptedGTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldKeyPemEncrypted, v))
}

// KeyPemEncryptedLT applies the LT predicate on the "key_pem_encrypted" field.
func KeyPemEncryptedLT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldKeyPemEncrypted, v))
}

// KeyPemEncryptedLTE applies the LTE predicate on the "key_pem_encrypted" field.
func KeyPemEncryptedLTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldKeyPemEncrypted, v))
}

// KeyPemEncryptedContains applies the Contains predicate on the "key_pem_encrypted" field.
func KeyPemEncryptedContains(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContains(FieldKeyPemEncrypted, v))
}

// KeyPemEncryptedHasPrefix applies the HasPrefix predicate on the "key_pem_encrypted" field.
func KeyPemEncryptedHasPrefix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasPrefix(FieldKeyPemEncrypted, v))
}

// KeyPemEncryptedHasSuffix applies the HasSuffix predicate on the "key_pem_encrypted" field.
func KeyPemEncryptedHasSuffix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasSuffix(FieldKeyPemEncrypted, v))
}

// KeyPemEncryptedIsNil applies the IsNil predicate on the "key_pem_encrypted" field.
func KeyPemEncryptedIsNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldIsNull(FieldKeyPemEncrypted))
}

// KeyPemEncryptedNotNil applies the NotNil predicate on the "key_pem_encrypted" field.
func KeyPemEncryptedNotNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldNotNull(FieldKeyPemEncrypted))
}

// KeyPemEncryptedEqualFold applies the EqualFold predicate on the "key_pem_encrypted" field.
func KeyPemEncryptedEqualFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEqualFold(FieldKeyPemEncrypted, v))
}

// KeyPemEncryptedContainsFold applies the ContainsFold predicate on the "key_pem_encrypted" field.
func KeyPemEncryptedContainsFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContainsFold(FieldKeyPemEncrypted, v))
}

// CertPemEQ applies the EQ predicate on the "cert_pem" field.
func CertPemEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldCertPem, v))
}

// CertPemNEQ applies the NEQ predicate on the "cert_pem" field.
func CertPemNEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldCertPem, v))
}

// CertPemIn applies the In predicate on the "cert_pem" field.
func CertPemIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldCertPem, vs...))
}

// CertPemNotIn applies the NotIn predicate on the "cert_pem" field.
func CertPemNotIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldCertPem, vs...))
}

// CertPemGT applies the GT predicate on the "cert_pem" field.
func CertPemGT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldCertPem, v))
}

// CertPemGTE applies the GTE predicate on the "cert_pem" field.
func CertPemGTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldCertPem, v))
}

// CertPemLT applies the LT predicate on the "cert_pem" field.
func CertPemLT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldCertPem, v))
}

// CertPemLTE applies the LTE predicate on the "cert_pem" field.
func CertPemLTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldCertPem, v))
}

// CertPemContains applies the Contains predicate on the "cert_pem" field.
func CertPemContains(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContains(FieldCertPem, v))
}

// CertPemHasPrefix applies the HasPrefix predicate on the "cert_pem" field.
func CertPemHasPrefix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasPrefix(FieldCertPem, v))
}

// CertPemHasSuffix applies the HasSuffix predicate on the "cert_pem" field.
func CertPemHasSuffix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasSuffix(FieldCertPem, v))
}

// CertPemEqualFold applies the EqualFold predicate on the "cert_pem" field.
func CertPemEqualFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEqualFold(FieldCertPem, v))
}

// CertPemContainsFold applies the ContainsFold predicate on the "cert_pem" field.
func CertPemContainsFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContainsFold(FieldCertPem, v))
}

// CrlPemEQ applies the EQ predicate on the "crl_pem" field.
func CrlPemEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldCrlPem, v))
}

// CrlPemNEQ applies the NEQ predicate on the "crl_pem" field.
func CrlPemNEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldCrlPem, v))
}

// CrlPemIn applies the In predicate on the "crl_pem" field.
func CrlPemIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldCrlPem, vs...))
}

// CrlPemNotIn applies the NotIn predicate on the "crl_pem" field.
func CrlPemNotIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldCrlPem, vs...))
}

// CrlPemGT applies the GT predicate on the "crl_pem" field.
func CrlPemGT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldCrlPem, v))
}

// CrlPemGTE applies the GTE predicate on the "crl_pem" field.
func CrlPemGTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldCrlPem, v))
}

// CrlPemLT applies the LT predicate on the "crl_pem" field.
func CrlPemLT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldCrlPem, v))
}

// CrlPemLTE applies the LTE predicate on the "crl_pem" field.
func CrlPemLTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldCrlPem, v))
}

// CrlPemContains applies the Contains predicate on the "crl_pem" field.
func CrlPemContains(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContains(FieldCrlPem, v))
}

// CrlPemHasPrefix applies the HasPrefix predicate on the "crl_pem" field.
func CrlPemHasPrefix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasPrefix(FieldCrlPem, v))
}

// CrlPemHasSuffix applies the HasSuffix predicate on the "crl_pem" field.
func CrlPemHasSuffix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasSuffix(FieldCrlPem, v))
}

// CrlPemIsNil applies the IsNil predicate on the "crl_pem" field.
func CrlPemIsNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldIsNull(FieldCrlPem))
}

// CrlPemNotNil applies the NotNil predicate on the "crl_pem" field.
func CrlPemNotNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldNotNull(FieldCrlPem))
}

// CrlPemEqualFold applies the EqualFold predicate on the "crl_pem" field.
func CrlPemEqualFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEqualFold(FieldCrlPem, v))
}

// CrlPemContainsFold applies the ContainsFold predicate on the "crl_pem" field.
func CrlPemContainsFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContainsFold(FieldCrlPem, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldStatus, vs...))
}

// KeyAlgorithmEQ applies the EQ predicate on the "key_algorithm" field.
func KeyAlgorithmEQ(v KeyAlgorithm) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldKeyAlgorithm, v))
}

// KeyAlgorithmNEQ applies the NEQ predicate on the "key_algorithm" field.
func KeyAlgorithmNEQ(v KeyAlgorithm) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldKeyAlgorithm, v))
}

// KeyAlgorithmIn applies the In predicate on the "key_algorithm" field.
func KeyAlgorithmIn(vs ...KeyAlgorithm) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldKeyAlgorithm, vs...))
}

// KeyAlgorithmNotIn applies the NotIn predicate on the "key_algorithm" field.
func KeyAlgorithmNotIn(vs ...KeyAlgorithm) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldKeyAlgorithm, vs...))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldNotNull(FieldRevokedAt))
}

// RevocationReasonEQ applies the EQ predicate on the "revocation_reason" field.
func RevocationReasonEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEQ(FieldRevocationReason, v))
}

// RevocationReasonNEQ applies the NEQ predicate on the "revocation_reason" field.
func RevocationReasonNEQ(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNEQ(FieldRevocationReason, v))
}

// RevocationReasonIn applies the In predicate on the "revocation_reason" field.
func RevocationReasonIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldIn(FieldRevocationReason, vs...))
}

// RevocationReasonNotIn applies the NotIn predicate on the "revocation_reason" field.
func RevocationReasonNotIn(vs ...string) predicate.Certificate {
	return predicate.Certificate(sql.FieldNotIn(FieldRevocationReason, vs...))
}

// RevocationReasonGT applies the GT predicate on the "revocation_reason" field.
func RevocationReasonGT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGT(FieldRevocationReason, v))
}

// RevocationReasonGTE applies the GTE predicate on the "revocation_reason" field.
func RevocationReasonGTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldGTE(FieldRevocationReason, v))
}

// RevocationReasonLT applies the LT predicate on the "revocation_reason" field.
func RevocationReasonLT(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLT(FieldRevocationReason, v))
}

// RevocationReasonLTE applies the LTE predicate on the "revocation_reason" field.
func RevocationReasonLTE(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldLTE(FieldRevocationReason, v))
}

// RevocationReasonContains applies the Contains predicate on the "revocation_reason" field.
func RevocationReasonContains(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContains(FieldRevocationReason, v))
}

// RevocationReasonHasPrefix applies the HasPrefix predicate on the "revocation_reason" field.
func RevocationReasonHasPrefix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasPrefix(FieldRevocationReason, v))
}

// RevocationReasonHasSuffix applies the HasSuffix predicate on the "revocation_reason" field.
func RevocationReasonHasSuffix(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldHasSuffix(FieldRevocationReason, v))
}

// RevocationReasonIsNil applies the IsNil predicate on the "revocation_reason" field.
func RevocationReasonIsNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldIsNull(FieldRevocationReason))
}

// RevocationReasonNotNil applies the NotNil predicate on the "revocation_reason" field.
func RevocationReasonNotNil() predicate.Certificate {
	return predicate.Certificate(sql.FieldNotNull(FieldRevocationReason))
}

// RevocationReasonEqualFold applies the EqualFold predicate on the "revocation_reason" field.
func RevocationReasonEqualFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldEqualFold(FieldRevocationReason, v))
}

// RevocationReasonContainsFold applies the ContainsFold predicate on the "revocation_reason" field.
func RevocationReasonContainsFold(v string) predicate.Certificate {
	return predicate.Certificate(sql.FieldContainsFold(FieldRevocationReason, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Certificate) predicate.Certificate {
	return predicate.Certificate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Certificate) predicate.Certificate {
	return predicate.Certificate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Certificate) predicate.Certificate {
	return predicate.Certificate(sql.NotPredicates(p))
}
