// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"context"

	"github.com/go-tangra/go-tangra-signing/internal/data/ent/certificate"
	"github.com/go-tangra/go-tangra-signing/internal/data/ent/event"
	"github.com/go-tangra/go-tangra-signing/internal/data/ent/schema"
	"github.com/go-tangra/go-tangra-signing/internal/data/ent/submission"
	"github.com/go-tangra/go-tangra-signing/internal/data/ent/submitter"
	"github.com/go-tangra/go-tangra-signing/internal/data/ent/template"
	"github.com/go-tangra/go-tangra-signing/internal/data/ent/templatefolder"

	"entgo.io/ent"
	"entgo.io/ent/privacy"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	certificateMixin := schema.Certificate{}.Mixin()
	certificate.Policy = privacy.NewPolicies(certificateMixin[2], schema.Certificate{})
	certificate.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := certificate.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	certificateMixinFields2 := certificateMixin[2].Fields()
	_ = certificateMixinFields2
	certificateFields := schema.Certificate{}.Fields()
	_ = certificateFields
	// certificateDescTenantID is the schema descriptor for tenant_id field.
	certificateDescTenantID := certificateMixinFields2[0].Descriptor()
	// certificate.DefaultTenantID holds the default value on creation for the tenant_id field.
	certificate.DefaultTenantID = certificateDescTenantID.Default.(uint32)
	// certificateDescSubjectCn is the schema descriptor for subject_cn field.
	certificateDescSubjectCn := certificateFields[1].Descriptor()
	// certificate.SubjectCnValidator is a validator for the "subject_cn" field. It is called by the builders before save.
	certificate.SubjectCnValidator = func() func(string) error {
		validators := certificateDescSubjectCn.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(subject_cn string) error {
			for _, fn := range fns {
				if err := fn(subject_cn); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// certificateDescSubjectOrg is the schema descriptor for subject_org field.
	certificateDescSubjectOrg := certificateFields[2].Descriptor()
	// certificate.SubjectOrgValidator is a validator for the "subject_org" field. It is called by the builders before save.
	certificate.SubjectOrgValidator = certificateDescSubjectOrg.Validators[0].(func(string) error)
	// certificateDescSerialNumber is the schema descriptor for serial_number field.
	certificateDescSerialNumber := certificateFields[3].Descriptor()
	// certificate.SerialNumberValidator is a validator for the "serial_number" field. It is called by the builders before save.
	certificate.SerialNumberValidator = func() func(string) error {
		validators := certificateDescSerialNumber.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(serial_number string) error {
			for _, fn := range fns {
				if err := fn(serial_number); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// certificateDescIsCa is the schema descriptor for is_ca field.
	certificateDescIsCa := certificateFields[6].Descriptor()
	// certificate.DefaultIsCa holds the default value on creation for the is_ca field.
	certificate.DefaultIsCa = certificateDescIsCa.Default.(bool)
	// certificateDescCertPem is the schema descriptor for cert_pem field.
	certificateDescCertPem := certificateFields[9].Descriptor()
	// certificate.CertPemValidator is a validator for the "cert_pem" field. It is called by the builders before save.
	certificate.CertPemValidator = certificateDescCertPem.Validators[0].(func(string) error)
	// certificateDescRevocationReason is the schema descriptor for revocation_reason field.
	certificateDescRevocationReason := certificateFields[14].Descriptor()
	// certificate.RevocationReasonValidator is a validator for the "revocation_reason" field. It is called by the builders before save.
	certificate.RevocationReasonValidator = certificateDescRevocationReason.Validators[0].(func(string) error)
	// certificateDescID is the schema descriptor for id field.
	certificateDescID := certificateFields[0].Descriptor()
	// certificate.IDValidator is a validator for the "id" field. It is called by the builders before save.
	certificate.IDValidator = certificateDescID.Validators[0].(func(string) error)
	eventMixin := schema.Event{}.Mixin()
	event.Policy = privacy.NewPolicies(eventMixin[1], schema.Event{})
	event.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := event.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	eventMixinFields1 := eventMixin[1].Fields()
	_ = eventMixinFields1
	eventFields := schema.Event{}.Fields()
	_ = eventFields
	// eventDescTenantID is the schema descriptor for tenant_id field.
	eventDescTenantID := eventMixinFields1[0].Descriptor()
	// event.DefaultTenantID holds the default value on creation for the tenant_id field.
	event.DefaultTenantID = eventDescTenantID.Default.(uint32)
	// eventDescEventType is the schema descriptor for event_type field.
	eventDescEventType := eventFields[1].Descriptor()
	// event.EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	event.EventTypeValidator = func() func(string) error {
		validators := eventDescEventType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(event_type string) error {
			for _, fn := range fns {
				if err := fn(event_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// eventDescActorID is the schema descriptor for actor_id field.
	eventDescActorID := eventFields[2].Descriptor()
	// event.ActorIDValidator is a validator for the "actor_id" field. It is called by the builders before save.
	event.ActorIDValidator = eventDescActorID.Validators[0].(func(string) error)
	// eventDescResourceType is the schema descriptor for resource_type field.
	eventDescResourceType := eventFields[3].Descriptor()
	// event.ResourceTypeValidator is a validator for the "resource_type" field. It is called by the builders before save.
	event.ResourceTypeValidator = func() func(string) error {
		validators := eventDescResourceType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(resource_type string) error {
			for _, fn := range fns {
				if err := fn(resource_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// eventDescResourceID is the schema descriptor for resource_id field.
	eventDescResourceID := eventFields[4].Descriptor()
	// event.ResourceIDValidator is a validator for the "resource_id" field. It is called by the builders before save.
	event.ResourceIDValidator = func() func(string) error {
		validators := eventDescResourceID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(resource_id string) error {
			for _, fn := range fns {
				if err := fn(resource_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// eventDescSubmissionID is the schema descriptor for submission_id field.
	eventDescSubmissionID := eventFields[5].Descriptor()
	// event.SubmissionIDValidator is a validator for the "submission_id" field. It is called by the builders before save.
	event.SubmissionIDValidator = eventDescSubmissionID.Validators[0].(func(string) error)
	// eventDescIP is the schema descriptor for ip field.
	eventDescIP := eventFields[7].Descriptor()
	// event.IPValidator is a validator for the "ip" field. It is called by the builders before save.
	event.IPValidator = eventDescIP.Validators[0].(func(string) error)
	// eventDescID is the schema descriptor for id field.
	eventDescID := eventFields[0].Descriptor()
	// event.IDValidator is a validator for the "id" field. It is called by the builders before save.
	event.IDValidator = eventDescID.Validators[0].(func(string) error)
	submissionMixin := schema.Submission{}.Mixin()
	submission.Policy = privacy.NewPolicies(submissionMixin[3], schema.Submission{})
	submission.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := submission.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	submissionMixinFields3 := submissionMixin[3].Fields()
	_ = submissionMixinFields3
	submissionFields := schema.Submission{}.Fields()
	_ = submissionFields
	// submissionDescTenantID is the schema descriptor for tenant_id field.
	submissionDescTenantID := submissionMixinFields3[0].Descriptor()
	// submission.DefaultTenantID holds the default value on creation for the tenant_id field.
	submission.DefaultTenantID = submissionDescTenantID.Default.(uint32)
	// submissionDescTemplateID is the schema descriptor for template_id field.
	submissionDescTemplateID := submissionFields[1].Descriptor()
	// submission.TemplateIDValidator is a validator for the "template_id" field. It is called by the builders before save.
	submission.TemplateIDValidator = submissionDescTemplateID.Validators[0].(func(string) error)
	// submissionDescSlug is the schema descriptor for slug field.
	submissionDescSlug := submissionFields[2].Descriptor()
	// submission.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	submission.SlugValidator = func() func(string) error {
		validators := submissionDescSlug.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(slug string) error {
			for _, fn := range fns {
				if err := fn(slug); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// submissionDescSource is the schema descriptor for source field.
	submissionDescSource := submissionFields[11].Descriptor()
	// submission.SourceValidator is a validator for the "source" field. It is called by the builders before save.
	submission.SourceValidator = submissionDescSource.Validators[0].(func(string) error)
	// submissionDescCurrentPdfKey is the schema descriptor for current_pdf_key field.
	submissionDescCurrentPdfKey := submissionFields[12].Descriptor()
	// submission.CurrentPdfKeyValidator is a validator for the "current_pdf_key" field. It is called by the builders before save.
	submission.CurrentPdfKeyValidator = submissionDescCurrentPdfKey.Validators[0].(func(string) error)
	// submissionDescSignedDocumentKey is the schema descriptor for signed_document_key field.
	submissionDescSignedDocumentKey := submissionFields[13].Descriptor()
	// submission.SignedDocumentKeyValidator is a validator for the "signed_document_key" field. It is called by the builders before save.
	submission.SignedDocumentKeyValidator = submissionDescSignedDocumentKey.Validators[0].(func(string) error)
	// submissionDescAuditTrailKey is the schema descriptor for audit_trail_key field.
	submissionDescAuditTrailKey := submissionFields[14].Descriptor()
	// submission.AuditTrailKeyValidator is a validator for the "audit_trail_key" field. It is called by the builders before save.
	submission.AuditTrailKeyValidator = submissionDescAuditTrailKey.Validators[0].(func(string) error)
	// submissionDescID is the schema descriptor for id field.
	submissionDescID := submissionFields[0].Descriptor()
	// submission.IDValidator is a validator for the "id" field. It is called by the builders before save.
	submission.IDValidator = submissionDescID.Validators[0].(func(string) error)
	submitterMixin := schema.Submitter{}.Mixin()
	submitter.Policy = privacy.NewPolicies(submitterMixin[1], schema.Submitter{})
	submitter.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := submitter.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	submitterMixinFields1 := submitterMixin[1].Fields()
	_ = submitterMixinFields1
	submitterFields := schema.Submitter{}.Fields()
	_ = submitterFields
	// submitterDescTenantID is the schema descriptor for tenant_id field.
	submitterDescTenantID := submitterMixinFields1[0].Descriptor()
	// submitter.DefaultTenantID holds the default value on creation for the tenant_id field.
	submitter.DefaultTenantID = submitterDescTenantID.Default.(uint32)
	// submitterDescSubmissionID is the schema descriptor for submission_id field.
	submitterDescSubmissionID := submitterFields[1].Descriptor()
	// submitter.SubmissionIDValidator is a validator for the "submission_id" field. It is called by the builders before save.
	submitter.SubmissionIDValidator = submitterDescSubmissionID.Validators[0].(func(string) error)
	// submitterDescName is the schema descriptor for name field.
	submitterDescName := submitterFields[2].Descriptor()
	// submitter.NameValidator is a validator for the "name" field. It is called by the builders before save.
	submitter.NameValidator = submitterDescName.Validators[0].(func(string) error)
	// submitterDescEmail is the schema descriptor for email field.
	submitterDescEmail := submitterFields[3].Descriptor()
	// submitter.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	submitter.EmailValidator = submitterDescEmail.Validators[0].(func(string) error)
	// submitterDescPhone is the schema descriptor for phone field.
	submitterDescPhone := submitterFields[4].Descriptor()
	// submitter.PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	submitter.PhoneValidator = submitterDescPhone.Validators[0].(func(string) error)
	// submitterDescSlug is the schema descriptor for slug field.
	submitterDescSlug := submitterFields[5].Descriptor()
	// submitter.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	submitter.SlugValidator = func() func(string) error {
		validators := submitterDescSlug.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(slug string) error {
			for _, fn := range fns {
				if err := fn(slug); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// submitterDescSigningOrder is the schema descriptor for signing_order field.
	submitterDescSigningOrder := submitterFields[6].Descriptor()
	// submitter.DefaultSigningOrder holds the default value on creation for the signing_order field.
	submitter.DefaultSigningOrder = submitterDescSigningOrder.Default.(int)
	// submitterDescRole is the schema descriptor for role field.
	submitterDescRole := submitterFields[7].Descriptor()
	// submitter.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	submitter.RoleValidator = submitterDescRole.Validators[0].(func(string) error)
	// submitterDescIP is the schema descriptor for ip field.
	submitterDescIP := submitterFields[11].Descriptor()
	// submitter.IPValidator is a validator for the "ip" field. It is called by the builders before save.
	submitter.IPValidator = submitterDescIP.Validators[0].(func(string) error)
	// submitterDescUserAgent is the schema descriptor for user_agent field.
	submitterDescUserAgent := submitterFields[12].Descriptor()
	// submitter.UserAgentValidator is a validator for the "user_agent" field. It is called by the builders before save.
	submitter.UserAgentValidator = submitterDescUserAgent.Validators[0].(func(string) error)
	// submitterDescDeclineReason is the schema descriptor for decline_reason field.
	submitterDescDeclineReason := submitterFields[13].Descriptor()
	// submitter.DeclineReasonValidator is a validator for the "decline_reason" field. It is called by the builders before save.
	submitter.DeclineReasonValidator = submitterDescDeclineReason.Validators[0].(func(string) error)
	// submitterDescID is the schema descriptor for id field.
	submitterDescID := submitterFields[0].Descriptor()
	// submitter.IDValidator is a validator for the "id" field. It is called by the builders before save.
	submitter.IDValidator = submitterDescID.Validators[0].(func(string) error)
	templateMixin := schema.Template{}.Mixin()
	template.Policy = privacy.NewPolicies(templateMixin[3], schema.Template{})
	template.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := template.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	templateMixinFields3 := templateMixin[3].Fields()
	_ = templateMixinFields3
	templateFields := schema.Template{}.Fields()
	_ = templateFields
	// templateDescTenantID is the schema descriptor for tenant_id field.
	templateDescTenantID := templateMixinFields3[0].Descriptor()
	// template.DefaultTenantID holds the default value on creation for the tenant_id field.
	template.DefaultTenantID = templateDescTenantID.Default.(uint32)
	// templateDescName is the schema descriptor for name field.
	templateDescName := templateFields[2].Descriptor()
	// template.NameValidator is a validator for the "name" field. It is called by the builders before save.
	template.NameValidator = func() func(string) error {
		validators := templateDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// templateDescSlug is the schema descriptor for slug field.
	templateDescSlug := templateFields[3].Descriptor()
	// template.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	template.SlugValidator = func() func(string) error {
		validators := templateDescSlug.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(slug string) error {
			for _, fn := range fns {
				if err := fn(slug); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// templateDescDescription is the schema descriptor for description field.
	templateDescDescription := templateFields[4].Descriptor()
	// template.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	template.DescriptionValidator = templateDescDescription.Validators[0].(func(string) error)
	// templateDescFileKey is the schema descriptor for file_key field.
	templateDescFileKey := templateFields[5].Descriptor()
	// template.FileKeyValidator is a validator for the "file_key" field. It is called by the builders before save.
	template.FileKeyValidator = func() func(string) error {
		validators := templateDescFileKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(file_key string) error {
			for _, fn := range fns {
				if err := fn(file_key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// templateDescFileName is the schema descriptor for file_name field.
	templateDescFileName := templateFields[6].Descriptor()
	// template.FileNameValidator is a validator for the "file_name" field. It is called by the builders before save.
	template.FileNameValidator = func() func(string) error {
		validators := templateDescFileName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(file_name string) error {
			for _, fn := range fns {
				if err := fn(file_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// templateDescFileSize is the schema descriptor for file_size field.
	templateDescFileSize := templateFields[7].Descriptor()
	// template.DefaultFileSize holds the default value on creation for the file_size field.
	template.DefaultFileSize = templateDescFileSize.Default.(int64)
	// templateDescSource is the schema descriptor for source field.
	templateDescSource := templateFields[10].Descriptor()
	// template.SourceValidator is a validator for the "source" field. It is called by the builders before save.
	template.SourceValidator = templateDescSource.Validators[0].(func(string) error)
	// templateDescID is the schema descriptor for id field.
	templateDescID := templateFields[0].Descriptor()
	// template.IDValidator is a validator for the "id" field. It is called by the builders before save.
	template.IDValidator = templateDescID.Validators[0].(func(string) error)
	templatefolderMixin := schema.TemplateFolder{}.Mixin()
	templatefolder.Policy = privacy.NewPolicies(templatefolderMixin[2], schema.TemplateFolder{})
	templatefolder.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := templatefolder.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	templatefolderMixinFields2 := templatefolderMixin[2].Fields()
	_ = templatefolderMixinFields2
	templatefolderFields := schema.TemplateFolder{}.Fields()
	_ = templatefolderFields
	// templatefolderDescTenantID is the schema descriptor for tenant_id field.
	templatefolderDescTenantID := templatefolderMixinFields2[0].Descriptor()
	// templatefolder.DefaultTenantID holds the default value on creation for the tenant_id field.
	templatefolder.DefaultTenantID = templatefolderDescTenantID.Default.(uint32)
	// templatefolderDescName is the schema descriptor for name field.
	templatefolderDescName := templatefolderFields[2].Descriptor()
	// templatefolder.NameValidator is a validator for the "name" field. It is called by the builders before save.
	templatefolder.NameValidator = func() func(string) error {
		validators := templatefolderDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// templatefolderDescPath is the schema descriptor for path field.
	templatefolderDescPath := templatefolderFields[3].Descriptor()
	// templatefolder.PathValidator is a validator for the "path" field. It is called by the builders before save.
	templatefolder.PathValidator = templatefolderDescPath.Validators[0].(func(string) error)
	// templatefolderDescDepth is the schema descriptor for depth field.
	templatefolderDescDepth := templatefolderFields[4].Descriptor()
	// templatefolder.DefaultDepth holds the default value on creation for the depth field.
	templatefolder.DefaultDepth = templatefolderDescDepth.Default.(int)
	// templatefolderDescSortOrder is the schema descriptor for sort_order field.
	templatefolderDescSortOrder := templatefolderFields[5].Descriptor()
	// templatefolder.DefaultSortOrder holds the default value on creation for the sort_order field.
	templatefolder.DefaultSortOrder = templatefolderDescSortOrder.Default.(int)
	// templatefolderDescID is the schema descriptor for id field.
	templatefolderDescID := templatefolderFields[0].Descriptor()
	// templatefolder.IDValidator is a validator for the "id" field. It is called by the builders before save.
	templatefolder.IDValidator = templatefolderDescID.Validators[0].(func(string) error)
}

const (
	Version = "v0.14.5"                                         // Version of ent codegen.
	Sum     = "h1:Rj2WOYJtCkWyFo6a+5wB3EfBRP0rnx1fMk6gGA0UUe4=" // Sum of ent codegen.
)
