// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-signing/internal/data/ent/certificate"
)

// CertificateCreate is the builder for creating a Certificate entity.
type CertificateCreate struct {
	config
	mutation *CertificateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateBy sets the "create_by" field.
func (_c *CertificateCreate) SetCreateBy(v uint32) *CertificateCreate {
	_c.mutation.SetCreateBy(v)
	return _c
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_c *CertificateCreate) SetNillableCreateBy(v *uint32) *CertificateCreate {
	if v != nil {
		_c.SetCreateBy(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *CertificateCreate) SetCreateTime(v time.Time) *CertificateCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *CertificateCreate) SetNillableCreateTime(v *time.Time) *CertificateCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *CertificateCreate) SetUpdateTime(v time.Time) *CertificateCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *CertificateCreate) SetNillableUpdateTime(v *time.Time) *CertificateCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetDeleteTime sets the "delete_time" field.
func (_c *CertificateCreate) SetDeleteTime(v time.Time) *CertificateCreate {
	_c.mutation.SetDeleteTime(v)
	return _c
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_c *CertificateCreate) SetNillableDeleteTime(v *time.Time) *CertificateCreate {
	if v != nil {
		_c.SetDeleteTime(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *CertificateCreate) SetTenantID(v uint32) *CertificateCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *CertificateCreate) SetNillableTenantID(v *uint32) *CertificateCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetSubjectCn sets the "subject_cn" field.
func (_c *CertificateCreate) SetSubjectCn(v string) *CertificateCreate {
	_c.mutation.SetSubjectCn(v)
	return _c
}

// SetSubjectOrg sets the "subject_org" field.
func (_c *CertificateCreate) SetSubjectOrg(v string) *CertificateCreate {
	_c.mutation.SetSubjectOrg(v)
	return _c
}

// SetNillableSubjectOrg sets the "subject_org" field if the given value is not nil.
func (_c *CertificateCreate) SetNillableSubjectOrg(v *string) *CertificateCreate {
	if v != nil {
		_c.SetSubjectOrg(*v)
	}
	return _c
}

// SetSerialNumber sets the "serial_number" field.
func (_c *CertificateCreate) SetSerialNumber(v string) *CertificateCreate {
	_c.mutation.SetSerialNumber(v)
	return _c
}

// SetNotBefore sets the "not_before" field.
func (_c *CertificateCreate) SetNotBefore(v time.Time) *CertificateCreate {
	_c.mutation.SetNotBefore(v)
	return _c
}

// SetNotAfter sets the "not_after" field.
func (_c *CertificateCreate) SetNotAfter(v time.Time) *CertificateCreate {
	_c.mutation.SetNotAfter(v)
	return _c
}

// SetIsCa sets the "is_ca" field.
func (_c *CertificateCreate) SetIsCa(v bool) *CertificateCreate {
	_c.mutation.SetIsCa(v)
	return _c
}

// SetNillableIsCa sets the "is_ca" field if the given value is not nil.
func (_c *CertificateCreate) SetNillableIsCa(v *bool) *CertificateCreate {
	if v != nil {
		_c.SetIsCa(*v)
	}
	return _c
}

// SetParentID sets the "parent_id" field.
func (_c *CertificateCreate) SetParentID(v string) *CertificateCreate {
	_c.mutation.SetParentID(v)
	return _c
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_c *CertificateCreate) SetNillableParentID(v *string) *CertificateCreate {
	if v != nil {
		_c.SetParentID(*v)
	}
	return _c
}

// SetKeyPemEncrypted sets the "key_pem_encrypted" field.
func (_c *CertificateCreate) SetKeyPemEncrypted(v string) *CertificateCreate {
	_c.mutation.SetKeyPemEncrypted(v)
	return _c
}

// SetNillableKeyPemEncrypted sets the "key_pem_encrypted" field if the given value is not nil.
func (_c *CertificateCreate) SetNillableKeyPemEncrypted(v *string) *CertificateCreate {
	if v != nil {
		_c.SetKeyPemEncrypted(*v)
	}
	return _c
}

// SetCertPem sets the "cert_pem" field.
func (_c *CertificateCreate) SetCertPem(v string) *CertificateCreate {
	_c.mutation.SetCertPem(v)
	return _c
}

// SetCrlPem sets the "crl_pem" field.
func (_c *CertificateCreate) SetCrlPem(v string) *CertificateCreate {
	_c.mutation.SetCrlPem(v)
	return _c
}

// SetNillableCrlPem sets the "crl_pem" field if the given value is not nil.
func (_c *CertificateCreate) SetNillableCrlPem(v *string) *CertificateCreate {
	if v != nil {
		_c.SetCrlPem(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *CertificateCreate) SetStatus(v certificate.Status) *CertificateCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *CertificateCreate) SetNillableStatus(v *certificate.Status) *CertificateCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetKeyAlgorithm sets the "key_algorithm" field.
func (_c *CertificateCreate) SetKeyAlgorithm(v certificate.KeyAlgorithm) *CertificateCreate {
	_c.mutation.SetKeyAlgorithm(v)
	return _c
}

// SetNillableKeyAlgorithm sets the "key_algorithm" field if the given value is not nil.
func (_c *CertificateCreate) SetNillableKeyAlgorithm(v *certificate.KeyAlgorithm) *CertificateCreate {
	if v != nil {
		_c.SetKeyAlgorithm(*v)
	}
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *CertificateCreate) SetRevokedAt(v time.Time) *CertificateCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *CertificateCreate) SetNillableRevokedAt(v *time.Time) *CertificateCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// SetRevocationReason sets the "revocation_reason" field.
func (_c *CertificateCreate) SetRevocationReason(v string) *CertificateCreate {
	_c.mutation.SetRevocationReason(v)
	return _c
}

// SetNillableRevocationReason sets the "revocation_reason" field if the given value is not nil.
func (_c *CertificateCreate) SetNillableRevocationReason(v *string) *CertificateCreate {
	if v != nil {
		_c.SetRevocationReason(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CertificateCreate) SetID(v string) *CertificateCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the CertificateMutation object of the builder.
func (_c *CertificateCreate) Mutation() *CertificateMutation {
	return _c.mutation
}

// Save creates the Certificate in the database.
func (_c *CertificateCreate) Save(ctx context.Context) (*Certificate, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CertificateCreate) SaveX(ctx context.Context) *Certificate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CertificateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CertificateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CertificateCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := certificate.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.IsCa(); !ok {
		v := certificate.DefaultIsCa
		_c.mutation.SetIsCa(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := certificate.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.KeyAlgorithm(); !ok {
		v := certificate.DefaultKeyAlgorithm
		_c.mutation.SetKeyAlgorithm(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *CertificateCreate) check() error {
	if _, ok := _c.mutation.SubjectCn(); !ok {
		return &ValidationError{Name: "subject_cn", err: errors.New(`ent: missing required field "Certificate.subject_cn"`)}
	}
	if v, ok := _c.mutation.SubjectCn(); ok {
		if err := certificate.SubjectCnValidator(v); err != nil {
			return &ValidationError{Name: "subject_cn", err: fmt.Errorf(`ent: validator failed for field "Certificate.subject_cn": %w`, err)}
		}
	}
	if v, ok := _c.mutation.SubjectOrg(); ok {
		if err := certificate.SubjectOrgValidator(v); err != nil {
			return &ValidationError{Name: "subject_org", err: fmt.Errorf(`ent: validator failed for field "Certificate.subject_org": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SerialNumber(); !ok {
		return &ValidationError{Name: "serial_number", err: errors.New(`ent: missing required field "Certificate.serial_number"`)}
	}
	if v, ok := _c.mutation.SerialNumber(); ok {
		if err := certificate.SerialNumberValidator(v); err != nil {
			return &ValidationError{Name: "serial_number", err: fmt.Errorf(`ent: validator failed for field "Certificate.serial_number": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NotBefore(); !ok {
		return &ValidationError{Name: "not_before", err: errors.New(`ent: missing required field "Certificate.not_before"`)}
	}
	if _, ok := _c.mutation.NotAfter(); !ok {
		return &ValidationError{Name: "not_after", err: errors.New(`ent: missing required field "Certificate.not_after"`)}
	}
	if _, ok := _c.mutation.IsCa(); !ok {
		return &ValidationError{Name: "is_ca", err: errors.New(`ent: missing required field "Certificate.is_ca"`)}
	}
	if _, ok := _c.mutation.CertPem(); !ok {
		return &ValidationError{Name: "cert_pem", err: errors.New(`ent: missing required field "Certificate.cert_pem"`)}
	}
	if v, ok := _c.mutation.CertPem(); ok {
		if err := certificate.CertPemValidator(v); err != nil {
			return &ValidationError{Name: "cert_pem", err: fmt.Errorf(`ent: validator failed for field "Certificate.cert_pem": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Certificate.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := certificate.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Certificate.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.KeyAlgorithm(); !ok {
		return &ValidationError{Name: "key_algorithm", err: errors.New(`ent: missing required field "Certificate.key_algorithm"`)}
	}
	if v, ok := _c.mutation.KeyAlgorithm(); ok {
		if err := certificate.KeyAlgorithmValidator(v); err != nil {
			return &ValidationError{Name: "key_algorithm", err: fmt.Errorf(`ent: validator failed for field "Certificate.key_algorithm": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RevocationReason(); ok {
		if err := certificate.RevocationReasonValidator(v); err != nil {
			return &ValidationError{Name: "revocation_reason", err: fmt.Errorf(`ent: validator failed for field "Certificate.revocation_reason": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := certificate.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Certificate.id": %w`, err)}
		}
	}
	return nil
}

func (_c *CertificateCreate) sqlSave(ctx context.Context) (*Certificate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Certificate.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CertificateCreate) createSpec() (*Certificate, *sqlgraph.CreateSpec) {
	var (
		_node = &Certificate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(certificate.Table, sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateBy(); ok {
		_spec.SetField(certificate.FieldCreateBy, field.TypeUint32, value)
		_node.CreateBy = &value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(certificate.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = &value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(certificate.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = &value
	}
	if value, ok := _c.mutation.DeleteTime(); ok {
		_spec.SetField(certificate.FieldDeleteTime, field.TypeTime, value)
		_node.DeleteTime = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(certificate.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.SubjectCn(); ok {
		_spec.SetField(certificate.FieldSubjectCn, field.TypeString, value)
		_node.SubjectCn = value
	}
	if value, ok := _c.mutation.SubjectOrg(); ok {
		_spec.SetField(certificate.FieldSubjectOrg, field.TypeString, value)
		_node.SubjectOrg = value
	}
	if value, ok := _c.mutation.SerialNumber(); ok {
		_spec.SetField(certificate.FieldSerialNumber, field.TypeString, value)
		_node.SerialNumber = value
	}
	if value, ok := _c.mutation.NotBefore(); ok {
		_spec.SetField(certificate.FieldNotBefore, field.TypeTime, value)
		_node.NotBefore = value
	}
	if value, ok := _c.mutation.NotAfter(); ok {
		_spec.SetField(certificate.FieldNotAfter, field.TypeTime, value)
		_node.NotAfter = value
	}
	if value, ok := _c.mutation.IsCa(); ok {
		_spec.SetField(certificate.FieldIsCa, field.TypeBool, value)
		_node.IsCa = value
	}
	if value, ok := _c.mutation.ParentID(); ok {
		_spec.SetField(certificate.FieldParentID, field.TypeString, value)
		_node.ParentID = &value
	}
	if value, ok := _c.mutation.KeyPemEncrypted(); ok {
		_spec.SetField(certificate.FieldKeyPemEncrypted, field.TypeString, value)
		_node.KeyPemEncrypted = value
	}
	if value, ok := _c.mutation.CertPem(); ok {
		_spec.SetField(certificate.FieldCertPem, field.TypeString, value)
		_node.CertPem = value
	}
	if value, ok := _c.mutation.CrlPem(); ok {
		_spec.SetField(certificate.FieldCrlPem, field.TypeString, value)
		_node.CrlPem = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(certificate.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.KeyAlgorithm(); ok {
		_spec.SetField(certificate.FieldKeyAlgorithm, field.TypeEnum, value)
		_node.KeyAlgorithm = value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(certificate.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	if value, ok := _c.mutation.RevocationReason(); ok {
		_spec.SetField(certificate.FieldRevocationReason, field.TypeString, value)
		_node.RevocationReason = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Certificate.Create().
//		SetCreateBy(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CertificateUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *CertificateCreate) OnConflict(opts ...sql.ConflictOption) *CertificateUpsertOne {
	_c.conflict = opts
	return &CertificateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Certificate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CertificateCreate) OnConflictColumns(columns ...string) *CertificateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CertificateUpsertOne{
		create: _c,
	}
}

type (
	// CertificateUpsertOne is the builder for "upsert"-ing
	//  one Certificate node.
	CertificateUpsertOne struct {
		create *CertificateCreate
	}

	// CertificateUpsert is the "OnConflict" setter.
	CertificateUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreateBy sets the "create_by" field.
func (u *CertificateUpsert) SetCreateBy(v uint32) *CertificateUpsert {
	u.Set(certificate.FieldCreateBy, v)
	return u
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *CertificateUpsert) UpdateCreateBy() *CertificateUpsert {
	u.SetExcluded(certificate.FieldCreateBy)
	return u
}

// AddCreateBy adds v to the "create_by" field.
func (u *CertificateUpsert) AddCreateBy(v uint32) *CertificateUpsert {
	u.Add(certificate.FieldCreateBy, v)
	return u
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *CertificateUpsert) ClearCreateBy() *CertificateUpsert {
	u.SetNull(certificate.FieldCreateBy)
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *CertificateUpsert) SetUpdateTime(v time.Time) *CertificateUpsert {
	u.Set(certificate.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *CertificateUpsert) UpdateUpdateTime() *CertificateUpsert {
	u.SetExcluded(certificate.FieldUpdateTime)
	return u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *CertificateUpsert) ClearUpdateTime() *CertificateUpsert {
	u.SetNull(certificate.FieldUpdateTime)
	return u
}

// SetDeleteTime sets the "delete_time" field.
func (u *CertificateUpsert) SetDeleteTime(v time.Time) *CertificateUpsert {
	u.Set(certificate.FieldDeleteTime, v)
	return u
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *CertificateUpsert) UpdateDeleteTime() *CertificateUpsert {
	u.SetExcluded(certificate.FieldDeleteTime)
	return u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *CertificateUpsert) ClearDeleteTime() *CertificateUpsert {
	u.SetNull(certificate.FieldDeleteTime)
	return u
}

// SetSubjectCn sets the "subject_cn" field.
func (u *CertificateUpsert) SetSubjectCn(v string) *CertificateUpsert {
	u.Set(certificate.FieldSubjectCn, v)
	return u
}

// UpdateSubjectCn sets the "subject_cn" field to the value that was provided on create.
func (u *CertificateUpsert) UpdateSubjectCn() *CertificateUpsert {
	u.SetExcluded(certificate.FieldSubjectCn)
	return u
}

// SetSubjectOrg sets the "subject_org" field.
func (u *CertificateUpsert) SetSubjectOrg(v string) *CertificateUpsert {
	u.Set(certificate.FieldSubjectOrg, v)
	return u
}

// UpdateSubjectOrg sets the "subject_org" field to the value that was provided on create.
func (u *CertificateUpsert) UpdateSubjectOrg() *CertificateUpsert {
	u.SetExcluded(certificate.FieldSubjectOrg)
	return u
}

// ClearSubjectOrg clears the value of the "subject_org" field.
func (u *CertificateUpsert) ClearSubjectOrg() *CertificateUpsert {
	u.SetNull(certificate.FieldSubjectOrg)
	return u
}

// SetSerialNumber sets the "serial_number" field.
func (u *CertificateUpsert) SetSerialNumber(v string) *CertificateUpsert {
	u.Set(certificate.FieldSerialNumber, v)
	return u
}

// UpdateSerialNumber sets the "serial_number" field to the value that was provided on create.
func (u *CertificateUpsert) UpdateSerialNumber() *CertificateUpsert {
	u.SetExcluded(certificate.FieldSerialNumber)
	return u
}

// SetNotBefore sets the "not_before" field.
func (u *CertificateUpsert) SetNotBefore(v time.Time) *CertificateUpsert {
	u.Set(certificate.FieldNotBefore, v)
	return u
}

// UpdateNotBefore sets the "not_before" field to the value that was provided on create.
func (u *CertificateUpsert) UpdateNotBefore() *CertificateUpsert {
	u.SetExcluded(certificate.FieldNotBefore)
	return u
}

// SetNotAfter sets the "not_after" field.
func (u *CertificateUpsert) SetNotAfter(v time.Time) *CertificateUpsert {
	u.Set(certificate.FieldNotAfter, v)
	return u
}

// UpdateNotAfter sets the "not_after" field to the value that was provided on create.
func (u *CertificateUpsert) UpdateNotAfter() *CertificateUpsert {
	u.SetExcluded(certificate.FieldNotAfter)
	return u
}

// SetIsCa sets the "is_ca" field.
func (u *CertificateUpsert) SetIsCa(v bool) *CertificateUpsert {
	u.Set(certificate.FieldIsCa, v)
	return u
}

// UpdateIsCa sets the "is_ca" field to the value that was provided on create.
func (u *CertificateUpsert) UpdateIsCa() *CertificateUpsert {
	u.SetExcluded(certificate.FieldIsCa)
	return u
}

// SetParentID sets the "parent_id" field.
func (u *CertificateUpsert) SetParentID(v string) *CertificateUpsert {
	u.Set(certificate.FieldParentID, v)
	return u
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *CertificateUpsert) UpdateParentID() *CertificateUpsert {
	u.SetExcluded(certificate.FieldParentID)
	return u
}

// ClearParentID clears the value of the "parent_id" field.
func (u *CertificateUpsert) ClearParentID() *CertificateUpsert {
	u.SetNull(certificate.FieldParentID)
	return u
}

// SetKeyPemEncrypted sets the "key_pem_encrypted" field.
func (u *CertificateUpsert) SetKeyPemEncrypted(v string) *CertificateUpsert {
	u.Set(certificate.FieldKeyPemEncrypted, v)
	return u
}

// UpdateKeyPemEncrypted sets the "key_pem_encrypted" field to the value that was provided on create.
func (u *CertificateUpsert) UpdateKeyPemEncrypted() *CertificateUpsert {
	u.SetExcluded(certificate.FieldKeyPemEncrypted)
	return u
}

// ClearKeyPemEncrypted clears the value of the "key_pem_encrypted" field.
func (u *CertificateUpsert) ClearKeyPemEncrypted() *CertificateUpsert {
	u.SetNull(certificate.FieldKeyPemEncrypted)
	return u
}

// SetCertPem sets the "cert_pem" field.
func (u *CertificateUpsert) SetCertPem(v string) *CertificateUpsert {
	u.Set(certificate.FieldCertPem, v)
	return u
}

// UpdateCertPem sets the "cert_pem" field to the value that was provided on create.
func (u *CertificateUpsert) UpdateCertPem() *CertificateUpsert {
	u.SetExcluded(certificate.FieldCertPem)
	return u
}

// SetCrlPem sets the "crl_pem" field.
func (u *CertificateUpsert) SetCrlPem(v string) *CertificateUpsert {
	u.Set(certificate.FieldCrlPem, v)
	return u
}

// UpdateCrlPem sets the "crl_pem" field to the value that was provided on create.
func (u *CertificateUpsert) UpdateCrlPem() *CertificateUpsert {
	u.SetExcluded(certificate.FieldCrlPem)
	return u
}

// ClearCrlPem clears the value of the "crl_pem" field.
func (u *CertificateUpsert) ClearCrlPem() *CertificateUpsert {
	u.SetNull(certificate.FieldCrlPem)
	return u
}

// SetStatus sets the "status" field.
func (u *CertificateUpsert) SetStatus(v certificate.Status) *CertificateUpsert {
	u.Set(certificate.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CertificateUpsert) UpdateStatus() *CertificateUpsert {
	u.SetExcluded(certificate.FieldStatus)
	return u
}

// SetKeyAlgorithm sets the "key_algorithm" field.
func (u *CertificateUpsert) SetKeyAlgorithm(v certificate.KeyAlgorithm) *CertificateUpsert {
	u.Set(certificate.FieldKeyAlgorithm, v)
	return u
}

// UpdateKeyAlgorithm sets the "key_algorithm" field to the value that was provided on create.
func (u *CertificateUpsert) UpdateKeyAlgorithm() *CertificateUpsert {
	u.SetExcluded(certificate.FieldKeyAlgorithm)
	return u
}

// SetRevokedAt sets the "revoked_at" field.
func (u *CertificateUpsert) SetRevokedAt(v time.Time) *CertificateUpsert {
	u.Set(certificate.FieldRevokedAt, v)
	return u
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *CertificateUpsert) UpdateRevokedAt() *CertificateUpsert {
	u.SetExcluded(certificate.FieldRevokedAt)
	return u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *CertificateUpsert) ClearRevokedAt() *CertificateUpsert {
	u.SetNull(certificate.FieldRevokedAt)
	return u
}

// SetRevocationReason sets the "revocation_reason" field.
func (u *CertificateUpsert) SetRevocationReason(v string) *CertificateUpsert {
	u.Set(certificate.FieldRevocationReason, v)
	return u
}

// UpdateRevocationReason sets the "revocation_reason" field to the value that was provided on create.
func (u *CertificateUpsert) UpdateRevocationReason() *CertificateUpsert {
	u.SetExcluded(certificate.FieldRevocationReason)
	return u
}

// ClearRevocationReason clears the value of the "revocation_reason" field.
func (u *CertificateUpsert) ClearRevocationReason() *CertificateUpsert {
	u.SetNull(certificate.FieldRevocationReason)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Certificate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(certificate.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CertificateUpsertOne) UpdateNewValues() *CertificateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(certificate.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(certificate.FieldCreateTime)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(certificate.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Certificate.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CertificateUpsertOne) Ignore() *CertificateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CertificateUpsertOne) DoNothing() *CertificateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CertificateCreate.OnConflict
// documentation for more info.
func (u *CertificateUpsertOne) Update(set func(*CertificateUpsert)) *CertificateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CertificateUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *CertificateUpsertOne) SetCreateBy(v uint32) *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *CertificateUpsertOne) AddCreateBy(v uint32) *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *CertificateUpsertOne) UpdateCreateBy() *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *CertificateUpsertOne) ClearCreateBy() *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *CertificateUpsertOne) SetUpdateTime(v time.Time) *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *CertificateUpsertOne) UpdateUpdateTime() *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *CertificateUpsertOne) ClearUpdateTime() *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *CertificateUpsertOne) SetDeleteTime(v time.Time) *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *CertificateUpsertOne) UpdateDeleteTime() *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *CertificateUpsertOne) ClearDeleteTime() *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.ClearDeleteTime()
	})
}

// SetSubjectCn sets the "subject_cn" field.
func (u *CertificateUpsertOne) SetSubjectCn(v string) *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.SetSubjectCn(v)
	})
}

// UpdateSubjectCn sets the "subject_cn" field to the value that was provided on create.
func (u *CertificateUpsertOne) UpdateSubjectCn() *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.UpdateSubjectCn()
	})
}

// SetSubjectOrg sets the "subject_org" field.
func (u *CertificateUpsertOne) SetSubjectOrg(v string) *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.SetSubjectOrg(v)
	})
}

// UpdateSubjectOrg sets the "subject_org" field to the value that was provided on create.
func (u *CertificateUpsertOne) UpdateSubjectOrg() *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.UpdateSubjectOrg()
	})
}

// ClearSubjectOrg clears the value of the "subject_org" field.
func (u *CertificateUpsertOne) ClearSubjectOrg() *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.ClearSubjectOrg()
	})
}

// SetSerialNumber sets the "serial_number" field.
func (u *CertificateUpsertOne) SetSerialNumber(v string) *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.SetSerialNumber(v)
	})
}

// UpdateSerialNumber sets the "serial_number" field to the value that was provided on create.
func (u *CertificateUpsertOne) UpdateSerialNumber() *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.UpdateSerialNumber()
	})
}

// SetNotBefore sets the "not_before" field.
func (u *CertificateUpsertOne) SetNotBefore(v time.Time) *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.SetNotBefore(v)
	})
}

// UpdateNotBefore sets the "not_before" field to the value that was provided on create.
func (u *CertificateUpsertOne) UpdateNotBefore() *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.UpdateNotBefore()
	})
}

// SetNotAfter sets the "not_after" field.
func (u *CertificateUpsertOne) SetNotAfter(v time.Time) *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.SetNotAfter(v)
	})
}

// UpdateNotAfter sets the "not_after" field to the value that was provided on create.
func (u *CertificateUpsertOne) UpdateNotAfter() *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.UpdateNotAfter()
	})
}

// SetIsCa sets the "is_ca" field.
func (u *CertificateUpsertOne) SetIsCa(v bool) *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.SetIsCa(v)
	})
}

// UpdateIsCa sets the "is_ca" field to the value that was provided on create.
func (u *CertificateUpsertOne) UpdateIsCa() *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.UpdateIsCa()
	})
}

// SetParentID sets the "parent_id" field.
func (u *CertificateUpsertOne) SetParentID(v string) *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.SetParentID(v)
	})
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *CertificateUpsertOne) UpdateParentID() *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.UpdateParentID()
	})
}

// ClearParentID clears the value of the "parent_id" field.
func (u *CertificateUpsertOne) ClearParentID() *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.ClearParentID()
	})
}

// SetKeyPemEncrypted sets the "key_pem_encrypted" field.
func (u *CertificateUpsertOne) SetKeyPemEncrypted(v string) *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.SetKeyPemEncrypted(v)
	})
}

// UpdateKeyPemEncrypted sets the "key_pem_encrypted" field to the value that was provided on create.
func (u *CertificateUpsertOne) UpdateKeyPemEncrypted() *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.UpdateKeyPemEncrypted()
	})
}

// ClearKeyPemEncrypted clears the value of the "key_pem_encrypted" field.
func (u *CertificateUpsertOne) ClearKeyPemEncrypted() *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.ClearKeyPemEncrypted()
	})
}

// SetCertPem sets the "cert_pem" field.
func (u *CertificateUpsertOne) SetCertPem(v string) *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.SetCertPem(v)
	})
}

// UpdateCertPem sets the "cert_pem" field to the value that was provided on create.
func (u *CertificateUpsertOne) UpdateCertPem() *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.UpdateCertPem()
	})
}

// SetCrlPem sets the "crl_pem" field.
func (u *CertificateUpsertOne) SetCrlPem(v string) *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.SetCrlPem(v)
	})
}

// UpdateCrlPem sets the "crl_pem" field to the value that was provided on create.
func (u *CertificateUpsertOne) UpdateCrlPem() *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.UpdateCrlPem()
	})
}

// ClearCrlPem clears the value of the "crl_pem" field.
func (u *CertificateUpsertOne) ClearCrlPem() *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.ClearCrlPem()
	})
}

// SetStatus sets the "status" field.
func (u *CertificateUpsertOne) SetStatus(v certificate.Status) *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CertificateUpsertOne) UpdateStatus() *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.UpdateStatus()
	})
}

// SetKeyAlgorithm sets the "key_algorithm" field.
func (u *CertificateUpsertOne) SetKeyAlgorithm(v certificate.KeyAlgorithm) *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.SetKeyAlgorithm(v)
	})
}

// UpdateKeyAlgorithm sets the "key_algorithm" field to the value that was provided on create.
func (u *CertificateUpsertOne) UpdateKeyAlgorithm() *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.UpdateKeyAlgorithm()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *CertificateUpsertOne) SetRevokedAt(v time.Time) *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *CertificateUpsertOne) UpdateRevokedAt() *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *CertificateUpsertOne) ClearRevokedAt() *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.ClearRevokedAt()
	})
}

// SetRevocationReason sets the "revocation_reason" field.
func (u *CertificateUpsertOne) SetRevocationReason(v string) *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.SetRevocationReason(v)
	})
}

// UpdateRevocationReason sets the "revocation_reason" field to the value that was provided on create.
func (u *CertificateUpsertOne) UpdateRevocationReason() *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.UpdateRevocationReason()
	})
}

// ClearRevocationReason clears the value of the "revocation_reason" field.
func (u *CertificateUpsertOne) ClearRevocationReason() *CertificateUpsertOne {
	return u.Update(func(s *CertificateUpsert) {
		s.ClearRevocationReason()
	})
}

// Exec executes the query.
func (u *CertificateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CertificateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CertificateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CertificateUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: CertificateUpsertOne.ID is not supported by MySQL driver. Use CertificateUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CertificateUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CertificateCreateBulk is the builder for creating many Certificate entities in bulk.
type CertificateCreateBulk struct {
	config
	err      error
	builders []*CertificateCreate
	conflict []sql.ConflictOption
}

// Save creates the Certificate entities in the database.
func (_c *CertificateCreateBulk) Save(ctx context.Context) ([]*Certificate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Certificate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CertificateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CertificateCreateBulk) SaveX(ctx context.Context) []*Certificate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CertificateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CertificateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Certificate.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CertificateUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *CertificateCreateBulk) OnConflict(opts ...sql.ConflictOption) *CertificateUpsertBulk {
	_c.conflict = opts
	return &CertificateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Certificate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CertificateCreateBulk) OnConflictColumns(columns ...string) *CertificateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CertificateUpsertBulk{
		create: _c,
	}
}

// CertificateUpsertBulk is the builder for "upsert"-ing
// a bulk of Certificate nodes.
type CertificateUpsertBulk struct {
	create *CertificateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Certificate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(certificate.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CertificateUpsertBulk) UpdateNewValues() *CertificateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(certificate.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(certificate.FieldCreateTime)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(certificate.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Certificate.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CertificateUpsertBulk) Ignore() *CertificateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CertificateUpsertBulk) DoNothing() *CertificateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CertificateCreateBulk.OnConflict
// documentation for more info.
func (u *CertificateUpsertBulk) Update(set func(*CertificateUpsert)) *CertificateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CertificateUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *CertificateUpsertBulk) SetCreateBy(v uint32) *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *CertificateUpsertBulk) AddCreateBy(v uint32) *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *CertificateUpsertBulk) UpdateCreateBy() *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *CertificateUpsertBulk) ClearCreateBy() *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *CertificateUpsertBulk) SetUpdateTime(v time.Time) *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *CertificateUpsertBulk) UpdateUpdateTime() *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *CertificateUpsertBulk) ClearUpdateTime() *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *CertificateUpsertBulk) SetDeleteTime(v time.Time) *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *CertificateUpsertBulk) UpdateDeleteTime() *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *CertificateUpsertBulk) ClearDeleteTime() *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.ClearDeleteTime()
	})
}

// SetSubjectCn sets the "subject_cn" field.
func (u *CertificateUpsertBulk) SetSubjectCn(v string) *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.SetSubjectCn(v)
	})
}

// UpdateSubjectCn sets the "subject_cn" field to the value that was provided on create.
func (u *CertificateUpsertBulk) UpdateSubjectCn() *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.UpdateSubjectCn()
	})
}

// SetSubjectOrg sets the "subject_org" field.
func (u *CertificateUpsertBulk) SetSubjectOrg(v string) *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.SetSubjectOrg(v)
	})
}

// UpdateSubjectOrg sets the "subject_org" field to the value that was provided on create.
func (u *CertificateUpsertBulk) UpdateSubjectOrg() *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.UpdateSubjectOrg()
	})
}

// ClearSubjectOrg clears the value of the "subject_org" field.
func (u *CertificateUpsertBulk) ClearSubjectOrg() *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.ClearSubjectOrg()
	})
}

// SetSerialNumber sets the "serial_number" field.
func (u *CertificateUpsertBulk) SetSerialNumber(v string) *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.SetSerialNumber(v)
	})
}

// UpdateSerialNumber sets the "serial_number" field to the value that was provided on create.
func (u *CertificateUpsertBulk) UpdateSerialNumber() *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.UpdateSerialNumber()
	})
}

// SetNotBefore sets the "not_before" field.
func (u *CertificateUpsertBulk) SetNotBefore(v time.Time) *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.SetNotBefore(v)
	})
}

// UpdateNotBefore sets the "not_before" field to the value that was provided on create.
func (u *CertificateUpsertBulk) UpdateNotBefore() *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.UpdateNotBefore()
	})
}

// SetNotAfter sets the "not_after" field.
func (u *CertificateUpsertBulk) SetNotAfter(v time.Time) *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.SetNotAfter(v)
	})
}

// UpdateNotAfter sets the "not_after" field to the value that was provided on create.
func (u *CertificateUpsertBulk) UpdateNotAfter() *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.UpdateNotAfter()
	})
}

// SetIsCa sets the "is_ca" field.
func (u *CertificateUpsertBulk) SetIsCa(v bool) *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.SetIsCa(v)
	})
}

// UpdateIsCa sets the "is_ca" field to the value that was provided on create.
func (u *CertificateUpsertBulk) UpdateIsCa() *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.UpdateIsCa()
	})
}

// SetParentID sets the "parent_id" field.
func (u *CertificateUpsertBulk) SetParentID(v string) *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.SetParentID(v)
	})
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *CertificateUpsertBulk) UpdateParentID() *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.UpdateParentID()
	})
}

// ClearParentID clears the value of the "parent_id" field.
func (u *CertificateUpsertBulk) ClearParentID() *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.ClearParentID()
	})
}

// SetKeyPemEncrypted sets the "key_pem_encrypted" field.
func (u *CertificateUpsertBulk) SetKeyPemEncrypted(v string) *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.SetKeyPemEncrypted(v)
	})
}

// UpdateKeyPemEncrypted sets the "key_pem_encrypted" field to the value that was provided on create.
func (u *CertificateUpsertBulk) UpdateKeyPemEncrypted() *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.UpdateKeyPemEncrypted()
	})
}

// ClearKeyPemEncrypted clears the value of the "key_pem_encrypted" field.
func (u *CertificateUpsertBulk) ClearKeyPemEncrypted() *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.ClearKeyPemEncrypted()
	})
}

// SetCertPem sets the "cert_pem" field.
func (u *CertificateUpsertBulk) SetCertPem(v string) *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.SetCertPem(v)
	})
}

// UpdateCertPem sets the "cert_pem" field to the value that was provided on create.
func (u *CertificateUpsertBulk) UpdateCertPem() *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.UpdateCertPem()
	})
}

// SetCrlPem sets the "crl_pem" field.
func (u *CertificateUpsertBulk) SetCrlPem(v string) *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.SetCrlPem(v)
	})
}

// UpdateCrlPem sets the "crl_pem" field to the value that was provided on create.
func (u *CertificateUpsertBulk) UpdateCrlPem() *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.UpdateCrlPem()
	})
}

// ClearCrlPem clears the value of the "crl_pem" field.
func (u *CertificateUpsertBulk) ClearCrlPem() *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.ClearCrlPem()
	})
}

// SetStatus sets the "status" field.
func (u *CertificateUpsertBulk) SetStatus(v certificate.Status) *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CertificateUpsertBulk) UpdateStatus() *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.UpdateStatus()
	})
}

// SetKeyAlgorithm sets the "key_algorithm" field.
func (u *CertificateUpsertBulk) SetKeyAlgorithm(v certificate.KeyAlgorithm) *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.SetKeyAlgorithm(v)
	})
}

// UpdateKeyAlgorithm sets the "key_algorithm" field to the value that was provided on create.
func (u *CertificateUpsertBulk) UpdateKeyAlgorithm() *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.UpdateKeyAlgorithm()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *CertificateUpsertBulk) SetRevokedAt(v time.Time) *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *CertificateUpsertBulk) UpdateRevokedAt() *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *CertificateUpsertBulk) ClearRevokedAt() *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.ClearRevokedAt()
	})
}

// SetRevocationReason sets the "revocation_reason" field.
func (u *CertificateUpsertBulk) SetRevocationReason(v string) *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.SetRevocationReason(v)
	})
}

// UpdateRevocationReason sets the "revocation_reason" field to the value that was provided on create.
func (u *CertificateUpsertBulk) UpdateRevocationReason() *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.UpdateRevocationReason()
	})
}

// ClearRevocationReason clears the value of the "revocation_reason" field.
func (u *CertificateUpsertBulk) ClearRevocationReason() *CertificateUpsertBulk {
	return u.Update(func(s *CertificateUpsert) {
		s.ClearRevocationReason()
	})
}

// Exec executes the query.
func (u *CertificateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CertificateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CertificateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CertificateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
