// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-signing/internal/data/ent/event"
	"github.com/go-tangra/go-tangra-signing/internal/data/ent/predicate"
	"github.com/go-tangra/go-tangra-signing/internal/data/ent/submission"
	"github.com/go-tangra/go-tangra-signing/internal/data/ent/submitter"
	"github.com/go-tangra/go-tangra-signing/internal/data/ent/template"
)

// SubmissionUpdate is the builder for updating Submission entities.
type SubmissionUpdate struct {
	config
	hooks     []Hook
	mutation  *SubmissionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SubmissionUpdate builder.
func (_u *SubmissionUpdate) Where(ps ...predicate.Submission) *SubmissionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreateBy sets the "create_by" field.
func (_u *SubmissionUpdate) SetCreateBy(v uint32) *SubmissionUpdate {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *SubmissionUpdate) SetNillableCreateBy(v *uint32) *SubmissionUpdate {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *SubmissionUpdate) AddCreateBy(v int32) *SubmissionUpdate {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *SubmissionUpdate) ClearCreateBy() *SubmissionUpdate {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *SubmissionUpdate) SetUpdateBy(v uint32) *SubmissionUpdate {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *SubmissionUpdate) SetNillableUpdateBy(v *uint32) *SubmissionUpdate {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *SubmissionUpdate) AddUpdateBy(v int32) *SubmissionUpdate {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (_u *SubmissionUpdate) ClearUpdateBy() *SubmissionUpdate {
	_u.mutation.ClearUpdateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *SubmissionUpdate) SetUpdateTime(v time.Time) *SubmissionUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *SubmissionUpdate) SetNillableUpdateTime(v *time.Time) *SubmissionUpdate {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *SubmissionUpdate) ClearUpdateTime() *SubmissionUpdate {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *SubmissionUpdate) SetDeleteTime(v time.Time) *SubmissionUpdate {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *SubmissionUpdate) SetNillableDeleteTime(v *time.Time) *SubmissionUpdate {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *SubmissionUpdate) ClearDeleteTime() *SubmissionUpdate {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetTemplateID sets the "template_id" field.
func (_u *SubmissionUpdate) SetTemplateID(v string) *SubmissionUpdate {
	_u.mutation.SetTemplateID(v)
	return _u
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_u *SubmissionUpdate) SetNillableTemplateID(v *string) *SubmissionUpdate {
	if v != nil {
		_u.SetTemplateID(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *SubmissionUpdate) SetSlug(v string) *SubmissionUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *SubmissionUpdate) SetNillableSlug(v *string) *SubmissionUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetSigningMode sets the "signing_mode" field.
func (_u *SubmissionUpdate) SetSigningMode(v submission.SigningMode) *SubmissionUpdate {
	_u.mutation.SetSigningMode(v)
	return _u
}

// SetNillableSigningMode sets the "signing_mode" field if the given value is not nil.
func (_u *SubmissionUpdate) SetNillableSigningMode(v *submission.SigningMode) *SubmissionUpdate {
	if v != nil {
		_u.SetSigningMode(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubmissionUpdate) SetStatus(v submission.Status) *SubmissionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubmissionUpdate) SetNillableStatus(v *submission.Status) *SubmissionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTemplateFieldsSnapshot sets the "template_fields_snapshot" field.
func (_u *SubmissionUpdate) SetTemplateFieldsSnapshot(v []map[string]interface{}) *SubmissionUpdate {
	_u.mutation.SetTemplateFieldsSnapshot(v)
	return _u
}

// AppendTemplateFieldsSnapshot appends value to the "template_fields_snapshot" field.
func (_u *SubmissionUpdate) AppendTemplateFieldsSnapshot(v []map[string]interface{}) *SubmissionUpdate {
	_u.mutation.AppendTemplateFieldsSnapshot(v)
	return _u
}

// ClearTemplateFieldsSnapshot clears the value of the "template_fields_snapshot" field.
func (_u *SubmissionUpdate) ClearTemplateFieldsSnapshot() *SubmissionUpdate {
	_u.mutation.ClearTemplateFieldsSnapshot()
	return _u
}

// SetTemplateSchemaSnapshot sets the "template_schema_snapshot" field.
func (_u *SubmissionUpdate) SetTemplateSchemaSnapshot(v map[string]interface{}) *SubmissionUpdate {
	_u.mutation.SetTemplateSchemaSnapshot(v)
	return _u
}

// ClearTemplateSchemaSnapshot clears the value of the "template_schema_snapshot" field.
func (_u *SubmissionUpdate) ClearTemplateSchemaSnapshot() *SubmissionUpdate {
	_u.mutation.ClearTemplateSchemaSnapshot()
	return _u
}

// SetTemplateSubmittersSnapshot sets the "template_submitters_snapshot" field.
func (_u *SubmissionUpdate) SetTemplateSubmittersSnapshot(v []map[string]interface{}) *SubmissionUpdate {
	_u.mutation.SetTemplateSubmittersSnapshot(v)
	return _u
}

// AppendTemplateSubmittersSnapshot appends value to the "template_submitters_snapshot" field.
func (_u *SubmissionUpdate) AppendTemplateSubmittersSnapshot(v []map[string]interface{}) *SubmissionUpdate {
	_u.mutation.AppendTemplateSubmittersSnapshot(v)
	return _u
}

// ClearTemplateSubmittersSnapshot clears the value of the "template_submitters_snapshot" field.
func (_u *SubmissionUpdate) ClearTemplateSubmittersSnapshot() *SubmissionUpdate {
	_u.mutation.ClearTemplateSubmittersSnapshot()
	return _u
}

// SetPreferences sets the "preferences" field.
func (_u *SubmissionUpdate) SetPreferences(v map[string]interface{}) *SubmissionUpdate {
	_u.mutation.SetPreferences(v)
	return _u
}

// ClearPreferences clears the value of the "preferences" field.
func (_u *SubmissionUpdate) ClearPreferences() *SubmissionUpdate {
	_u.mutation.ClearPreferences()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *SubmissionUpdate) SetCompletedAt(v time.Time) *SubmissionUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *SubmissionUpdate) SetNillableCompletedAt(v *time.Time) *SubmissionUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *SubmissionUpdate) ClearCompletedAt() *SubmissionUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *SubmissionUpdate) SetExpiresAt(v time.Time) *SubmissionUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *SubmissionUpdate) SetNillableExpiresAt(v *time.Time) *SubmissionUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *SubmissionUpdate) ClearExpiresAt() *SubmissionUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetSource sets the "source" field.
func (_u *SubmissionUpdate) SetSource(v string) *SubmissionUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *SubmissionUpdate) SetNillableSource(v *string) *SubmissionUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// ClearSource clears the value of the "source" field.
func (_u *SubmissionUpdate) ClearSource() *SubmissionUpdate {
	_u.mutation.ClearSource()
	return _u
}

// SetCurrentPdfKey sets the "current_pdf_key" field.
func (_u *SubmissionUpdate) SetCurrentPdfKey(v string) *SubmissionUpdate {
	_u.mutation.SetCurrentPdfKey(v)
	return _u
}

// SetNillableCurrentPdfKey sets the "current_pdf_key" field if the given value is not nil.
func (_u *SubmissionUpdate) SetNillableCurrentPdfKey(v *string) *SubmissionUpdate {
	if v != nil {
		_u.SetCurrentPdfKey(*v)
	}
	return _u
}

// ClearCurrentPdfKey clears the value of the "current_pdf_key" field.
func (_u *SubmissionUpdate) ClearCurrentPdfKey() *SubmissionUpdate {
	_u.mutation.ClearCurrentPdfKey()
	return _u
}

// SetSignedDocumentKey sets the "signed_document_key" field.
func (_u *SubmissionUpdate) SetSignedDocumentKey(v string) *SubmissionUpdate {
	_u.mutation.SetSignedDocumentKey(v)
	return _u
}

// SetNillableSignedDocumentKey sets the "signed_document_key" field if the given value is not nil.
func (_u *SubmissionUpdate) SetNillableSignedDocumentKey(v *string) *SubmissionUpdate {
	if v != nil {
		_u.SetSignedDocumentKey(*v)
	}
	return _u
}

// ClearSignedDocumentKey clears the value of the "signed_document_key" field.
func (_u *SubmissionUpdate) ClearSignedDocumentKey() *SubmissionUpdate {
	_u.mutation.ClearSignedDocumentKey()
	return _u
}

// SetAuditTrailKey sets the "audit_trail_key" field.
func (_u *SubmissionUpdate) SetAuditTrailKey(v string) *SubmissionUpdate {
	_u.mutation.SetAuditTrailKey(v)
	return _u
}

// SetNillableAuditTrailKey sets the "audit_trail_key" field if the given value is not nil.
func (_u *SubmissionUpdate) SetNillableAuditTrailKey(v *string) *SubmissionUpdate {
	if v != nil {
		_u.SetAuditTrailKey(*v)
	}
	return _u
}

// ClearAuditTrailKey clears the value of the "audit_trail_key" field.
func (_u *SubmissionUpdate) ClearAuditTrailKey() *SubmissionUpdate {
	_u.mutation.ClearAuditTrailKey()
	return _u
}

// SetTemplate sets the "template" edge to the Template entity.
func (_u *SubmissionUpdate) SetTemplate(v *Template) *SubmissionUpdate {
	return _u.SetTemplateID(v.ID)
}

// AddSubmitterIDs adds the "submitters" edge to the Submitter entity by IDs.
func (_u *SubmissionUpdate) AddSubmitterIDs(ids ...string) *SubmissionUpdate {
	_u.mutation.AddSubmitterIDs(ids...)
	return _u
}

// AddSubmitters adds the "submitters" edges to the Submitter entity.
func (_u *SubmissionUpdate) AddSubmitters(v ...*Submitter) *SubmissionUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubmitterIDs(ids...)
}

// AddEventIDs adds the "events" edge to the Event entity by IDs.
func (_u *SubmissionUpdate) AddEventIDs(ids ...string) *SubmissionUpdate {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the Event entity.
func (_u *SubmissionUpdate) AddEvents(v ...*Event) *SubmissionUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// Mutation returns the SubmissionMutation object of the builder.
func (_u *SubmissionUpdate) Mutation() *SubmissionMutation {
	return _u.mutation
}

// ClearTemplate clears the "template" edge to the Template entity.
func (_u *SubmissionUpdate) ClearTemplate() *SubmissionUpdate {
	_u.mutation.ClearTemplate()
	return _u
}

// ClearSubmitters clears all "submitters" edges to the Submitter entity.
func (_u *SubmissionUpdate) ClearSubmitters() *SubmissionUpdate {
	_u.mutation.ClearSubmitters()
	return _u
}

// RemoveSubmitterIDs removes the "submitters" edge to Submitter entities by IDs.
func (_u *SubmissionUpdate) RemoveSubmitterIDs(ids ...string) *SubmissionUpdate {
	_u.mutation.RemoveSubmitterIDs(ids...)
	return _u
}

// RemoveSubmitters removes "submitters" edges to Submitter entities.
func (_u *SubmissionUpdate) RemoveSubmitters(v ...*Submitter) *SubmissionUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubmitterIDs(ids...)
}

// ClearEvents clears all "events" edges to the Event entity.
func (_u *SubmissionUpdate) ClearEvents() *SubmissionUpdate {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to Event entities by IDs.
func (_u *SubmissionUpdate) RemoveEventIDs(ids ...string) *SubmissionUpdate {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to Event entities.
func (_u *SubmissionUpdate) RemoveEvents(v ...*Event) *SubmissionUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubmissionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubmissionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubmissionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubmissionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubmissionUpdate) check() error {
	if v, ok := _u.mutation.TemplateID(); ok {
		if err := submission.TemplateIDValidator(v); err != nil {
			return &ValidationError{Name: "template_id", err: fmt.Errorf(`ent: validator failed for field "Submission.template_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := submission.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Submission.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SigningMode(); ok {
		if err := submission.SigningModeValidator(v); err != nil {
			return &ValidationError{Name: "signing_mode", err: fmt.Errorf(`ent: validator failed for field "Submission.signing_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := submission.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Submission.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := submission.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Submission.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CurrentPdfKey(); ok {
		if err := submission.CurrentPdfKeyValidator(v); err != nil {
			return &ValidationError{Name: "current_pdf_key", err: fmt.Errorf(`ent: validator failed for field "Submission.current_pdf_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SignedDocumentKey(); ok {
		if err := submission.SignedDocumentKeyValidator(v); err != nil {
			return &ValidationError{Name: "signed_document_key", err: fmt.Errorf(`ent: validator failed for field "Submission.signed_document_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuditTrailKey(); ok {
		if err := submission.AuditTrailKeyValidator(v); err != nil {
			return &ValidationError{Name: "audit_trail_key", err: fmt.Errorf(`ent: validator failed for field "Submission.audit_trail_key": %w`, err)}
		}
	}
	if _u.mutation.TemplateCleared() && len(_u.mutation.TemplateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Submission.template"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SubmissionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SubmissionUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SubmissionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(submission.Table, submission.Columns, sqlgraph.NewFieldSpec(submission.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(submission.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(submission.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(submission.FieldCreateBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(submission.FieldUpdateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(submission.FieldUpdateBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdateByCleared() {
		_spec.ClearField(submission.FieldUpdateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(submission.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(submission.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(submission.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(submission.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(submission.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(submission.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(submission.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.SigningMode(); ok {
		_spec.SetField(submission.FieldSigningMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(submission.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TemplateFieldsSnapshot(); ok {
		_spec.SetField(submission.FieldTemplateFieldsSnapshot, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTemplateFieldsSnapshot(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, submission.FieldTemplateFieldsSnapshot, value)
		})
	}
	if _u.mutation.TemplateFieldsSnapshotCleared() {
		_spec.ClearField(submission.FieldTemplateFieldsSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.TemplateSchemaSnapshot(); ok {
		_spec.SetField(submission.FieldTemplateSchemaSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.TemplateSchemaSnapshotCleared() {
		_spec.ClearField(submission.FieldTemplateSchemaSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.TemplateSubmittersSnapshot(); ok {
		_spec.SetField(submission.FieldTemplateSubmittersSnapshot, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTemplateSubmittersSnapshot(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, submission.FieldTemplateSubmittersSnapshot, value)
		})
	}
	if _u.mutation.TemplateSubmittersSnapshotCleared() {
		_spec.ClearField(submission.FieldTemplateSubmittersSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.Preferences(); ok {
		_spec.SetField(submission.FieldPreferences, field.TypeJSON, value)
	}
	if _u.mutation.PreferencesCleared() {
		_spec.ClearField(submission.FieldPreferences, field.TypeJSON)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(submission.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(submission.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(submission.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(submission.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(submission.FieldSource, field.TypeString, value)
	}
	if _u.mutation.SourceCleared() {
		_spec.ClearField(submission.FieldSource, field.TypeString)
	}
	if value, ok := _u.mutation.CurrentPdfKey(); ok {
		_spec.SetField(submission.FieldCurrentPdfKey, field.TypeString, value)
	}
	if _u.mutation.CurrentPdfKeyCleared() {
		_spec.ClearField(submission.FieldCurrentPdfKey, field.TypeString)
	}
	if value, ok := _u.mutation.SignedDocumentKey(); ok {
		_spec.SetField(submission.FieldSignedDocumentKey, field.TypeString, value)
	}
	if _u.mutation.SignedDocumentKeyCleared() {
		_spec.ClearField(submission.FieldSignedDocumentKey, field.TypeString)
	}
	if value, ok := _u.mutation.AuditTrailKey(); ok {
		_spec.SetField(submission.FieldAuditTrailKey, field.TypeString, value)
	}
	if _u.mutation.AuditTrailKeyCleared() {
		_spec.ClearField(submission.FieldAuditTrailKey, field.TypeString)
	}
	if _u.mutation.TemplateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   submission.TemplateTable,
			Columns: []string{submission.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(template.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TemplateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   submission.TemplateTable,
			Columns: []string{submission.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(template.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubmittersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   submission.SubmittersTable,
			Columns: []string{submission.SubmittersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(submitter.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubmittersIDs(); len(nodes) > 0 && !_u.mutation.SubmittersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   submission.SubmittersTable,
			Columns: []string{submission.SubmittersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(submitter.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubmittersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   submission.SubmittersTable,
			Columns: []string{submission.SubmittersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(submitter.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   submission.EventsTable,
			Columns: []string{submission.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   submission.EventsTable,
			Columns: []string{submission.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   submission.EventsTable,
			Columns: []string{submission.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{submission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubmissionUpdateOne is the builder for updating a single Submission entity.
type SubmissionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SubmissionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreateBy sets the "create_by" field.
func (_u *SubmissionUpdateOne) SetCreateBy(v uint32) *SubmissionUpdateOne {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *SubmissionUpdateOne) SetNillableCreateBy(v *uint32) *SubmissionUpdateOne {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *SubmissionUpdateOne) AddCreateBy(v int32) *SubmissionUpdateOne {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *SubmissionUpdateOne) ClearCreateBy() *SubmissionUpdateOne {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *SubmissionUpdateOne) SetUpdateBy(v uint32) *SubmissionUpdateOne {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *SubmissionUpdateOne) SetNillableUpdateBy(v *uint32) *SubmissionUpdateOne {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *SubmissionUpdateOne) AddUpdateBy(v int32) *SubmissionUpdateOne {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (_u *SubmissionUpdateOne) ClearUpdateBy() *SubmissionUpdateOne {
	_u.mutation.ClearUpdateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *SubmissionUpdateOne) SetUpdateTime(v time.Time) *SubmissionUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *SubmissionUpdateOne) SetNillableUpdateTime(v *time.Time) *SubmissionUpdateOne {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *SubmissionUpdateOne) ClearUpdateTime() *SubmissionUpdateOne {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *SubmissionUpdateOne) SetDeleteTime(v time.Time) *SubmissionUpdateOne {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *SubmissionUpdateOne) SetNillableDeleteTime(v *time.Time) *SubmissionUpdateOne {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *SubmissionUpdateOne) ClearDeleteTime() *SubmissionUpdateOne {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetTemplateID sets the "template_id" field.
func (_u *SubmissionUpdateOne) SetTemplateID(v string) *SubmissionUpdateOne {
	_u.mutation.SetTemplateID(v)
	return _u
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_u *SubmissionUpdateOne) SetNillableTemplateID(v *string) *SubmissionUpdateOne {
	if v != nil {
		_u.SetTemplateID(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *SubmissionUpdateOne) SetSlug(v string) *SubmissionUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *SubmissionUpdateOne) SetNillableSlug(v *string) *SubmissionUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetSigningMode sets the "signing_mode" field.
func (_u *SubmissionUpdateOne) SetSigningMode(v submission.SigningMode) *SubmissionUpdateOne {
	_u.mutation.SetSigningMode(v)
	return _u
}

// SetNillableSigningMode sets the "signing_mode" field if the given value is not nil.
func (_u *SubmissionUpdateOne) SetNillableSigningMode(v *submission.SigningMode) *SubmissionUpdateOne {
	if v != nil {
		_u.SetSigningMode(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubmissionUpdateOne) SetStatus(v submission.Status) *SubmissionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubmissionUpdateOne) SetNillableStatus(v *submission.Status) *SubmissionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTemplateFieldsSnapshot sets the "template_fields_snapshot" field.
func (_u *SubmissionUpdateOne) SetTemplateFieldsSnapshot(v []map[string]interface{}) *SubmissionUpdateOne {
	_u.mutation.SetTemplateFieldsSnapshot(v)
	return _u
}

// AppendTemplateFieldsSnapshot appends value to the "template_fields_snapshot" field.
func (_u *SubmissionUpdateOne) AppendTemplateFieldsSnapshot(v []map[string]interface{}) *SubmissionUpdateOne {
	_u.mutation.AppendTemplateFieldsSnapshot(v)
	return _u
}

// ClearTemplateFieldsSnapshot clears the value of the "template_fields_snapshot" field.
func (_u *SubmissionUpdateOne) ClearTemplateFieldsSnapshot() *SubmissionUpdateOne {
	_u.mutation.ClearTemplateFieldsSnapshot()
	return _u
}

// SetTemplateSchemaSnapshot sets the "template_schema_snapshot" field.
func (_u *SubmissionUpdateOne) SetTemplateSchemaSnapshot(v map[string]interface{}) *SubmissionUpdateOne {
	_u.mutation.SetTemplateSchemaSnapshot(v)
	return _u
}

// ClearTemplateSchemaSnapshot clears the value of the "template_schema_snapshot" field.
func (_u *SubmissionUpdateOne) ClearTemplateSchemaSnapshot() *SubmissionUpdateOne {
	_u.mutation.ClearTemplateSchemaSnapshot()
	return _u
}

// SetTemplateSubmittersSnapshot sets the "template_submitters_snapshot" field.
func (_u *SubmissionUpdateOne) SetTemplateSubmittersSnapshot(v []map[string]interface{}) *SubmissionUpdateOne {
	_u.mutation.SetTemplateSubmittersSnapshot(v)
	return _u
}

// AppendTemplateSubmittersSnapshot appends value to the "template_submitters_snapshot" field.
func (_u *SubmissionUpdateOne) AppendTemplateSubmittersSnapshot(v []map[string]interface{}) *SubmissionUpdateOne {
	_u.mutation.AppendTemplateSubmittersSnapshot(v)
	return _u
}

// ClearTemplateSubmittersSnapshot clears the value of the "template_submitters_snapshot" field.
func (_u *SubmissionUpdateOne) ClearTemplateSubmittersSnapshot() *SubmissionUpdateOne {
	_u.mutation.ClearTemplateSubmittersSnapshot()
	return _u
}

// SetPreferences sets the "preferences" field.
func (_u *SubmissionUpdateOne) SetPreferences(v map[string]interface{}) *SubmissionUpdateOne {
	_u.mutation.SetPreferences(v)
	return _u
}

// ClearPreferences clears the value of the "preferences" field.
func (_u *SubmissionUpdateOne) ClearPreferences() *SubmissionUpdateOne {
	_u.mutation.ClearPreferences()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *SubmissionUpdateOne) SetCompletedAt(v time.Time) *SubmissionUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *SubmissionUpdateOne) SetNillableCompletedAt(v *time.Time) *SubmissionUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *SubmissionUpdateOne) ClearCompletedAt() *SubmissionUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *SubmissionUpdateOne) SetExpiresAt(v time.Time) *SubmissionUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *SubmissionUpdateOne) SetNillableExpiresAt(v *time.Time) *SubmissionUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *SubmissionUpdateOne) ClearExpiresAt() *SubmissionUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetSource sets the "source" field.
func (_u *SubmissionUpdateOne) SetSource(v string) *SubmissionUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *SubmissionUpdateOne) SetNillableSource(v *string) *SubmissionUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// ClearSource clears the value of the "source" field.
func (_u *SubmissionUpdateOne) ClearSource() *SubmissionUpdateOne {
	_u.mutation.ClearSource()
	return _u
}

// SetCurrentPdfKey sets the "current_pdf_key" field.
func (_u *SubmissionUpdateOne) SetCurrentPdfKey(v string) *SubmissionUpdateOne {
	_u.mutation.SetCurrentPdfKey(v)
	return _u
}

// SetNillableCurrentPdfKey sets the "current_pdf_key" field if the given value is not nil.
func (_u *SubmissionUpdateOne) SetNillableCurrentPdfKey(v *string) *SubmissionUpdateOne {
	if v != nil {
		_u.SetCurrentPdfKey(*v)
	}
	return _u
}

// ClearCurrentPdfKey clears the value of the "current_pdf_key" field.
func (_u *SubmissionUpdateOne) ClearCurrentPdfKey() *SubmissionUpdateOne {
	_u.mutation.ClearCurrentPdfKey()
	return _u
}

// SetSignedDocumentKey sets the "signed_document_key" field.
func (_u *SubmissionUpdateOne) SetSignedDocumentKey(v string) *SubmissionUpdateOne {
	_u.mutation.SetSignedDocumentKey(v)
	return _u
}

// SetNillableSignedDocumentKey sets the "signed_document_key" field if the given value is not nil.
func (_u *SubmissionUpdateOne) SetNillableSignedDocumentKey(v *string) *SubmissionUpdateOne {
	if v != nil {
		_u.SetSignedDocumentKey(*v)
	}
	return _u
}

// ClearSignedDocumentKey clears the value of the "signed_document_key" field.
func (_u *SubmissionUpdateOne) ClearSignedDocumentKey() *SubmissionUpdateOne {
	_u.mutation.ClearSignedDocumentKey()
	return _u
}

// SetAuditTrailKey sets the "audit_trail_key" field.
func (_u *SubmissionUpdateOne) SetAuditTrailKey(v string) *SubmissionUpdateOne {
	_u.mutation.SetAuditTrailKey(v)
	return _u
}

// SetNillableAuditTrailKey sets the "audit_trail_key" field if the given value is not nil.
func (_u *SubmissionUpdateOne) SetNillableAuditTrailKey(v *string) *SubmissionUpdateOne {
	if v != nil {
		_u.SetAuditTrailKey(*v)
	}
	return _u
}

// ClearAuditTrailKey clears the value of the "audit_trail_key" field.
func (_u *SubmissionUpdateOne) ClearAuditTrailKey() *SubmissionUpdateOne {
	_u.mutation.ClearAuditTrailKey()
	return _u
}

// SetTemplate sets the "template" edge to the Template entity.
func (_u *SubmissionUpdateOne) SetTemplate(v *Template) *SubmissionUpdateOne {
	return _u.SetTemplateID(v.ID)
}

// AddSubmitterIDs adds the "submitters" edge to the Submitter entity by IDs.
func (_u *SubmissionUpdateOne) AddSubmitterIDs(ids ...string) *SubmissionUpdateOne {
	_u.mutation.AddSubmitterIDs(ids...)
	return _u
}

// AddSubmitters adds the "submitters" edges to the Submitter entity.
func (_u *SubmissionUpdateOne) AddSubmitters(v ...*Submitter) *SubmissionUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubmitterIDs(ids...)
}

// AddEventIDs adds the "events" edge to the Event entity by IDs.
func (_u *SubmissionUpdateOne) AddEventIDs(ids ...string) *SubmissionUpdateOne {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the Event entity.
func (_u *SubmissionUpdateOne) AddEvents(v ...*Event) *SubmissionUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// Mutation returns the SubmissionMutation object of the builder.
func (_u *SubmissionUpdateOne) Mutation() *SubmissionMutation {
	return _u.mutation
}

// ClearTemplate clears the "template" edge to the Template entity.
func (_u *SubmissionUpdateOne) ClearTemplate() *SubmissionUpdateOne {
	_u.mutation.ClearTemplate()
	return _u
}

// ClearSubmitters clears all "submitters" edges to the Submitter entity.
func (_u *SubmissionUpdateOne) ClearSubmitters() *SubmissionUpdateOne {
	_u.mutation.ClearSubmitters()
	return _u
}

// RemoveSubmitterIDs removes the "submitters" edge to Submitter entities by IDs.
func (_u *SubmissionUpdateOne) RemoveSubmitterIDs(ids ...string) *SubmissionUpdateOne {
	_u.mutation.RemoveSubmitterIDs(ids...)
	return _u
}

// RemoveSubmitters removes "submitters" edges to Submitter entities.
func (_u *SubmissionUpdateOne) RemoveSubmitters(v ...*Submitter) *SubmissionUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubmitterIDs(ids...)
}

// ClearEvents clears all "events" edges to the Event entity.
func (_u *SubmissionUpdateOne) ClearEvents() *SubmissionUpdateOne {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to Event entities by IDs.
func (_u *SubmissionUpdateOne) RemoveEventIDs(ids ...string) *SubmissionUpdateOne {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to Event entities.
func (_u *SubmissionUpdateOne) RemoveEvents(v ...*Event) *SubmissionUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// Where appends a list predicates to the SubmissionUpdate builder.
func (_u *SubmissionUpdateOne) Where(ps ...predicate.Submission) *SubmissionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubmissionUpdateOne) Select(field string, fields ...string) *SubmissionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Submission entity.
func (_u *SubmissionUpdateOne) Save(ctx context.Context) (*Submission, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubmissionUpdateOne) SaveX(ctx context.Context) *Submission {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubmissionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubmissionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubmissionUpdateOne) check() error {
	if v, ok := _u.mutation.TemplateID(); ok {
		if err := submission.TemplateIDValidator(v); err != nil {
			return &ValidationError{Name: "template_id", err: fmt.Errorf(`ent: validator failed for field "Submission.template_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := submission.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Submission.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SigningMode(); ok {
		if err := submission.SigningModeValidator(v); err != nil {
			return &ValidationError{Name: "signing_mode", err: fmt.Errorf(`ent: validator failed for field "Submission.signing_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := submission.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Submission.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := submission.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Submission.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CurrentPdfKey(); ok {
		if err := submission.CurrentPdfKeyValidator(v); err != nil {
			return &ValidationError{Name: "current_pdf_key", err: fmt.Errorf(`ent: validator failed for field "Submission.current_pdf_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SignedDocumentKey(); ok {
		if err := submission.SignedDocumentKeyValidator(v); err != nil {
			return &ValidationError{Name: "signed_document_key", err: fmt.Errorf(`ent: validator failed for field "Submission.signed_document_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuditTrailKey(); ok {
		if err := submission.AuditTrailKeyValidator(v); err != nil {
			return &ValidationError{Name: "audit_trail_key", err: fmt.Errorf(`ent: validator failed for field "Submission.audit_trail_key": %w`, err)}
		}
	}
	if _u.mutation.TemplateCleared() && len(_u.mutation.TemplateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Submission.template"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SubmissionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SubmissionUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SubmissionUpdateOne) sqlSave(ctx context.Context) (_node *Submission, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(submission.Table, submission.Columns, sqlgraph.NewFieldSpec(submission.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Submission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, submission.FieldID)
		for _, f := range fields {
			if !submission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != submission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(submission.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(submission.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(submission.FieldCreateBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(submission.FieldUpdateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(submission.FieldUpdateBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdateByCleared() {
		_spec.ClearField(submission.FieldUpdateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(submission.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(submission.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(submission.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(submission.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(submission.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(submission.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(submission.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.SigningMode(); ok {
		_spec.SetField(submission.FieldSigningMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(submission.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TemplateFieldsSnapshot(); ok {
		_spec.SetField(submission.FieldTemplateFieldsSnapshot, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTemplateFieldsSnapshot(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, submission.FieldTemplateFieldsSnapshot, value)
		})
	}
	if _u.mutation.TemplateFieldsSnapshotCleared() {
		_spec.ClearField(submission.FieldTemplateFieldsSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.TemplateSchemaSnapshot(); ok {
		_spec.SetField(submission.FieldTemplateSchemaSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.TemplateSchemaSnapshotCleared() {
		_spec.ClearField(submission.FieldTemplateSchemaSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.TemplateSubmittersSnapshot(); ok {
		_spec.SetField(submission.FieldTemplateSubmittersSnapshot, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTemplateSubmittersSnapshot(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, submission.FieldTemplateSubmittersSnapshot, value)
		})
	}
	if _u.mutation.TemplateSubmittersSnapshotCleared() {
		_spec.ClearField(submission.FieldTemplateSubmittersSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.Preferences(); ok {
		_spec.SetField(submission.FieldPreferences, field.TypeJSON, value)
	}
	if _u.mutation.PreferencesCleared() {
		_spec.ClearField(submission.FieldPreferences, field.TypeJSON)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(submission.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(submission.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(submission.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(submission.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(submission.FieldSource, field.TypeString, value)
	}
	if _u.mutation.SourceCleared() {
		_spec.ClearField(submission.FieldSource, field.TypeString)
	}
	if value, ok := _u.mutation.CurrentPdfKey(); ok {
		_spec.SetField(submission.FieldCurrentPdfKey, field.TypeString, value)
	}
	if _u.mutation.CurrentPdfKeyCleared() {
		_spec.ClearField(submission.FieldCurrentPdfKey, field.TypeString)
	}
	if value, ok := _u.mutation.SignedDocumentKey(); ok {
		_spec.SetField(submission.FieldSignedDocumentKey, field.TypeString, value)
	}
	if _u.mutation.SignedDocumentKeyCleared() {
		_spec.ClearField(submission.FieldSignedDocumentKey, field.TypeString)
	}
	if value, ok := _u.mutation.AuditTrailKey(); ok {
		_spec.SetField(submission.FieldAuditTrailKey, field.TypeString, value)
	}
	if _u.mutation.AuditTrailKeyCleared() {
		_spec.ClearField(submission.FieldAuditTrailKey, field.TypeString)
	}
	if _u.mutation.TemplateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   submission.TemplateTable,
			Columns: []string{submission.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(template.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TemplateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   submission.TemplateTable,
			Columns: []string{submission.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(template.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubmittersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   submission.SubmittersTable,
			Columns: []string{submission.SubmittersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(submitter.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubmittersIDs(); len(nodes) > 0 && !_u.mutation.SubmittersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   submission.SubmittersTable,
			Columns: []string{submission.SubmittersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(submitter.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubmittersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   submission.SubmittersTable,
			Columns: []string{submission.SubmittersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(submitter.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   submission.EventsTable,
			Columns: []string{submission.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   submission.EventsTable,
			Columns: []string{submission.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   submission.EventsTable,
			Columns: []string{submission.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Submission{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{submission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
