// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-signing/internal/data/ent/event"
	"github.com/go-tangra/go-tangra-signing/internal/data/ent/submission"
	"github.com/go-tangra/go-tangra-signing/internal/data/ent/submitter"
	"github.com/go-tangra/go-tangra-signing/internal/data/ent/template"
)

// SubmissionCreate is the builder for creating a Submission entity.
type SubmissionCreate struct {
	config
	mutation *SubmissionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateBy sets the "create_by" field.
func (_c *SubmissionCreate) SetCreateBy(v uint32) *SubmissionCreate {
	_c.mutation.SetCreateBy(v)
	return _c
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_c *SubmissionCreate) SetNillableCreateBy(v *uint32) *SubmissionCreate {
	if v != nil {
		_c.SetCreateBy(*v)
	}
	return _c
}

// SetUpdateBy sets the "update_by" field.
func (_c *SubmissionCreate) SetUpdateBy(v uint32) *SubmissionCreate {
	_c.mutation.SetUpdateBy(v)
	return _c
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_c *SubmissionCreate) SetNillableUpdateBy(v *uint32) *SubmissionCreate {
	if v != nil {
		_c.SetUpdateBy(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *SubmissionCreate) SetCreateTime(v time.Time) *SubmissionCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *SubmissionCreate) SetNillableCreateTime(v *time.Time) *SubmissionCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *SubmissionCreate) SetUpdateTime(v time.Time) *SubmissionCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *SubmissionCreate) SetNillableUpdateTime(v *time.Time) *SubmissionCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetDeleteTime sets the "delete_time" field.
func (_c *SubmissionCreate) SetDeleteTime(v time.Time) *SubmissionCreate {
	_c.mutation.SetDeleteTime(v)
	return _c
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_c *SubmissionCreate) SetNillableDeleteTime(v *time.Time) *SubmissionCreate {
	if v != nil {
		_c.SetDeleteTime(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *SubmissionCreate) SetTenantID(v uint32) *SubmissionCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *SubmissionCreate) SetNillableTenantID(v *uint32) *SubmissionCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetTemplateID sets the "template_id" field.
func (_c *SubmissionCreate) SetTemplateID(v string) *SubmissionCreate {
	_c.mutation.SetTemplateID(v)
	return _c
}

// SetSlug sets the "slug" field.
func (_c *SubmissionCreate) SetSlug(v string) *SubmissionCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetSigningMode sets the "signing_mode" field.
func (_c *SubmissionCreate) SetSigningMode(v submission.SigningMode) *SubmissionCreate {
	_c.mutation.SetSigningMode(v)
	return _c
}

// SetNillableSigningMode sets the "signing_mode" field if the given value is not nil.
func (_c *SubmissionCreate) SetNillableSigningMode(v *submission.SigningMode) *SubmissionCreate {
	if v != nil {
		_c.SetSigningMode(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SubmissionCreate) SetStatus(v submission.Status) *SubmissionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SubmissionCreate) SetNillableStatus(v *submission.Status) *SubmissionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetTemplateFieldsSnapshot sets the "template_fields_snapshot" field.
func (_c *SubmissionCreate) SetTemplateFieldsSnapshot(v []map[string]interface{}) *SubmissionCreate {
	_c.mutation.SetTemplateFieldsSnapshot(v)
	return _c
}

// SetTemplateSchemaSnapshot sets the "template_schema_snapshot" field.
func (_c *SubmissionCreate) SetTemplateSchemaSnapshot(v map[string]interface{}) *SubmissionCreate {
	_c.mutation.SetTemplateSchemaSnapshot(v)
	return _c
}

// SetTemplateSubmittersSnapshot sets the "template_submitters_snapshot" field.
func (_c *SubmissionCreate) SetTemplateSubmittersSnapshot(v []map[string]interface{}) *SubmissionCreate {
	_c.mutation.SetTemplateSubmittersSnapshot(v)
	return _c
}

// SetPreferences sets the "preferences" field.
func (_c *SubmissionCreate) SetPreferences(v map[string]interface{}) *SubmissionCreate {
	_c.mutation.SetPreferences(v)
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *SubmissionCreate) SetCompletedAt(v time.Time) *SubmissionCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *SubmissionCreate) SetNillableCompletedAt(v *time.Time) *SubmissionCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *SubmissionCreate) SetExpiresAt(v time.Time) *SubmissionCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *SubmissionCreate) SetNillableExpiresAt(v *time.Time) *SubmissionCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *SubmissionCreate) SetSource(v string) *SubmissionCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *SubmissionCreate) SetNillableSource(v *string) *SubmissionCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetCurrentPdfKey sets the "current_pdf_key" field.
func (_c *SubmissionCreate) SetCurrentPdfKey(v string) *SubmissionCreate {
	_c.mutation.SetCurrentPdfKey(v)
	return _c
}

// SetNillableCurrentPdfKey sets the "current_pdf_key" field if the given value is not nil.
func (_c *SubmissionCreate) SetNillableCurrentPdfKey(v *string) *SubmissionCreate {
	if v != nil {
		_c.SetCurrentPdfKey(*v)
	}
	return _c
}

// SetSignedDocumentKey sets the "signed_document_key" field.
func (_c *SubmissionCreate) SetSignedDocumentKey(v string) *SubmissionCreate {
	_c.mutation.SetSignedDocumentKey(v)
	return _c
}

// SetNillableSignedDocumentKey sets the "signed_document_key" field if the given value is not nil.
func (_c *SubmissionCreate) SetNillableSignedDocumentKey(v *string) *SubmissionCreate {
	if v != nil {
		_c.SetSignedDocumentKey(*v)
	}
	return _c
}

// SetAuditTrailKey sets the "audit_trail_key" field.
func (_c *SubmissionCreate) SetAuditTrailKey(v string) *SubmissionCreate {
	_c.mutation.SetAuditTrailKey(v)
	return _c
}

// SetNillableAuditTrailKey sets the "audit_trail_key" field if the given value is not nil.
func (_c *SubmissionCreate) SetNillableAuditTrailKey(v *string) *SubmissionCreate {
	if v != nil {
		_c.SetAuditTrailKey(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SubmissionCreate) SetID(v string) *SubmissionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetTemplate sets the "template" edge to the Template entity.
func (_c *SubmissionCreate) SetTemplate(v *Template) *SubmissionCreate {
	return _c.SetTemplateID(v.ID)
}

// AddSubmitterIDs adds the "submitters" edge to the Submitter entity by IDs.
func (_c *SubmissionCreate) AddSubmitterIDs(ids ...string) *SubmissionCreate {
	_c.mutation.AddSubmitterIDs(ids...)
	return _c
}

// AddSubmitters adds the "submitters" edges to the Submitter entity.
func (_c *SubmissionCreate) AddSubmitters(v ...*Submitter) *SubmissionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSubmitterIDs(ids...)
}

// AddEventIDs adds the "events" edge to the Event entity by IDs.
func (_c *SubmissionCreate) AddEventIDs(ids ...string) *SubmissionCreate {
	_c.mutation.AddEventIDs(ids...)
	return _c
}

// AddEvents adds the "events" edges to the Event entity.
func (_c *SubmissionCreate) AddEvents(v ...*Event) *SubmissionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEventIDs(ids...)
}

// Mutation returns the SubmissionMutation object of the builder.
func (_c *SubmissionCreate) Mutation() *SubmissionMutation {
	return _c.mutation
}

// Save creates the Submission in the database.
func (_c *SubmissionCreate) Save(ctx context.Context) (*Submission, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubmissionCreate) SaveX(ctx context.Context) *Submission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubmissionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubmissionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubmissionCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := submission.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.SigningMode(); !ok {
		v := submission.DefaultSigningMode
		_c.mutation.SetSigningMode(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := submission.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubmissionCreate) check() error {
	if _, ok := _c.mutation.TemplateID(); !ok {
		return &ValidationError{Name: "template_id", err: errors.New(`ent: missing required field "Submission.template_id"`)}
	}
	if v, ok := _c.mutation.TemplateID(); ok {
		if err := submission.TemplateIDValidator(v); err != nil {
			return &ValidationError{Name: "template_id", err: fmt.Errorf(`ent: validator failed for field "Submission.template_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "Submission.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := submission.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Submission.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SigningMode(); !ok {
		return &ValidationError{Name: "signing_mode", err: errors.New(`ent: missing required field "Submission.signing_mode"`)}
	}
	if v, ok := _c.mutation.SigningMode(); ok {
		if err := submission.SigningModeValidator(v); err != nil {
			return &ValidationError{Name: "signing_mode", err: fmt.Errorf(`ent: validator failed for field "Submission.signing_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Submission.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := submission.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Submission.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := submission.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Submission.source": %w`, err)}
		}
	}
	if v, ok := _c.mutation.CurrentPdfKey(); ok {
		if err := submission.CurrentPdfKeyValidator(v); err != nil {
			return &ValidationError{Name: "current_pdf_key", err: fmt.Errorf(`ent: validator failed for field "Submission.current_pdf_key": %w`, err)}
		}
	}
	if v, ok := _c.mutation.SignedDocumentKey(); ok {
		if err := submission.SignedDocumentKeyValidator(v); err != nil {
			return &ValidationError{Name: "signed_document_key", err: fmt.Errorf(`ent: validator failed for field "Submission.signed_document_key": %w`, err)}
		}
	}
	if v, ok := _c.mutation.AuditTrailKey(); ok {
		if err := submission.AuditTrailKeyValidator(v); err != nil {
			return &ValidationError{Name: "audit_trail_key", err: fmt.Errorf(`ent: validator failed for field "Submission.audit_trail_key": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := submission.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Submission.id": %w`, err)}
		}
	}
	if len(_c.mutation.TemplateIDs()) == 0 {
		return &ValidationError{Name: "template", err: errors.New(`ent: missing required edge "Submission.template"`)}
	}
	return nil
}

func (_c *SubmissionCreate) sqlSave(ctx context.Context) (*Submission, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Submission.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubmissionCreate) createSpec() (*Submission, *sqlgraph.CreateSpec) {
	var (
		_node = &Submission{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(submission.Table, sqlgraph.NewFieldSpec(submission.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateBy(); ok {
		_spec.SetField(submission.FieldCreateBy, field.TypeUint32, value)
		_node.CreateBy = &value
	}
	if value, ok := _c.mutation.UpdateBy(); ok {
		_spec.SetField(submission.FieldUpdateBy, field.TypeUint32, value)
		_node.UpdateBy = &value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(submission.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = &value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(submission.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = &value
	}
	if value, ok := _c.mutation.DeleteTime(); ok {
		_spec.SetField(submission.FieldDeleteTime, field.TypeTime, value)
		_node.DeleteTime = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(submission.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(submission.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.SigningMode(); ok {
		_spec.SetField(submission.FieldSigningMode, field.TypeEnum, value)
		_node.SigningMode = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(submission.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.TemplateFieldsSnapshot(); ok {
		_spec.SetField(submission.FieldTemplateFieldsSnapshot, field.TypeJSON, value)
		_node.TemplateFieldsSnapshot = value
	}
	if value, ok := _c.mutation.TemplateSchemaSnapshot(); ok {
		_spec.SetField(submission.FieldTemplateSchemaSnapshot, field.TypeJSON, value)
		_node.TemplateSchemaSnapshot = value
	}
	if value, ok := _c.mutation.TemplateSubmittersSnapshot(); ok {
		_spec.SetField(submission.FieldTemplateSubmittersSnapshot, field.TypeJSON, value)
		_node.TemplateSubmittersSnapshot = value
	}
	if value, ok := _c.mutation.Preferences(); ok {
		_spec.SetField(submission.FieldPreferences, field.TypeJSON, value)
		_node.Preferences = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(submission.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(submission.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(submission.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.CurrentPdfKey(); ok {
		_spec.SetField(submission.FieldCurrentPdfKey, field.TypeString, value)
		_node.CurrentPdfKey = value
	}
	if value, ok := _c.mutation.SignedDocumentKey(); ok {
		_spec.SetField(submission.FieldSignedDocumentKey, field.TypeString, value)
		_node.SignedDocumentKey = value
	}
	if value, ok := _c.mutation.AuditTrailKey(); ok {
		_spec.SetField(submission.FieldAuditTrailKey, field.TypeString, value)
		_node.AuditTrailKey = value
	}
	if nodes := _c.mutation.TemplateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   submission.TemplateTable,
			Columns: []string{submission.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(template.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TemplateID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SubmittersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   submission.SubmittersTable,
			Columns: []string{submission.SubmittersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(submitter.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   submission.EventsTable,
			Columns: []string{submission.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Submission.Create().
//		SetCreateBy(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubmissionUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *SubmissionCreate) OnConflict(opts ...sql.ConflictOption) *SubmissionUpsertOne {
	_c.conflict = opts
	return &SubmissionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Submission.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubmissionCreate) OnConflictColumns(columns ...string) *SubmissionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubmissionUpsertOne{
		create: _c,
	}
}

type (
	// SubmissionUpsertOne is the builder for "upsert"-ing
	//  one Submission node.
	SubmissionUpsertOne struct {
		create *SubmissionCreate
	}

	// SubmissionUpsert is the "OnConflict" setter.
	SubmissionUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreateBy sets the "create_by" field.
func (u *SubmissionUpsert) SetCreateBy(v uint32) *SubmissionUpsert {
	u.Set(submission.FieldCreateBy, v)
	return u
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *SubmissionUpsert) UpdateCreateBy() *SubmissionUpsert {
	u.SetExcluded(submission.FieldCreateBy)
	return u
}

// AddCreateBy adds v to the "create_by" field.
func (u *SubmissionUpsert) AddCreateBy(v uint32) *SubmissionUpsert {
	u.Add(submission.FieldCreateBy, v)
	return u
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *SubmissionUpsert) ClearCreateBy() *SubmissionUpsert {
	u.SetNull(submission.FieldCreateBy)
	return u
}

// SetUpdateBy sets the "update_by" field.
func (u *SubmissionUpsert) SetUpdateBy(v uint32) *SubmissionUpsert {
	u.Set(submission.FieldUpdateBy, v)
	return u
}

// UpdateUpdateBy sets the "update_by" field to the value that was provided on create.
func (u *SubmissionUpsert) UpdateUpdateBy() *SubmissionUpsert {
	u.SetExcluded(submission.FieldUpdateBy)
	return u
}

// AddUpdateBy adds v to the "update_by" field.
func (u *SubmissionUpsert) AddUpdateBy(v uint32) *SubmissionUpsert {
	u.Add(submission.FieldUpdateBy, v)
	return u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (u *SubmissionUpsert) ClearUpdateBy() *SubmissionUpsert {
	u.SetNull(submission.FieldUpdateBy)
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *SubmissionUpsert) SetUpdateTime(v time.Time) *SubmissionUpsert {
	u.Set(submission.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *SubmissionUpsert) UpdateUpdateTime() *SubmissionUpsert {
	u.SetExcluded(submission.FieldUpdateTime)
	return u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *SubmissionUpsert) ClearUpdateTime() *SubmissionUpsert {
	u.SetNull(submission.FieldUpdateTime)
	return u
}

// SetDeleteTime sets the "delete_time" field.
func (u *SubmissionUpsert) SetDeleteTime(v time.Time) *SubmissionUpsert {
	u.Set(submission.FieldDeleteTime, v)
	return u
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *SubmissionUpsert) UpdateDeleteTime() *SubmissionUpsert {
	u.SetExcluded(submission.FieldDeleteTime)
	return u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *SubmissionUpsert) ClearDeleteTime() *SubmissionUpsert {
	u.SetNull(submission.FieldDeleteTime)
	return u
}

// SetTemplateID sets the "template_id" field.
func (u *SubmissionUpsert) SetTemplateID(v string) *SubmissionUpsert {
	u.Set(submission.FieldTemplateID, v)
	return u
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *SubmissionUpsert) UpdateTemplateID() *SubmissionUpsert {
	u.SetExcluded(submission.FieldTemplateID)
	return u
}

// SetSlug sets the "slug" field.
func (u *SubmissionUpsert) SetSlug(v string) *SubmissionUpsert {
	u.Set(submission.FieldSlug, v)
	return u
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *SubmissionUpsert) UpdateSlug() *SubmissionUpsert {
	u.SetExcluded(submission.FieldSlug)
	return u
}

// SetSigningMode sets the "signing_mode" field.
func (u *SubmissionUpsert) SetSigningMode(v submission.SigningMode) *SubmissionUpsert {
	u.Set(submission.FieldSigningMode, v)
	return u
}

// UpdateSigningMode sets the "signing_mode" field to the value that was provided on create.
func (u *SubmissionUpsert) UpdateSigningMode() *SubmissionUpsert {
	u.SetExcluded(submission.FieldSigningMode)
	return u
}

// SetStatus sets the "status" field.
func (u *SubmissionUpsert) SetStatus(v submission.Status) *SubmissionUpsert {
	u.Set(submission.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubmissionUpsert) UpdateStatus() *SubmissionUpsert {
	u.SetExcluded(submission.FieldStatus)
	return u
}

// SetTemplateFieldsSnapshot sets the "template_fields_snapshot" field.
func (u *SubmissionUpsert) SetTemplateFieldsSnapshot(v []map[string]interface{}) *SubmissionUpsert {
	u.Set(submission.FieldTemplateFieldsSnapshot, v)
	return u
}

// UpdateTemplateFieldsSnapshot sets the "template_fields_snapshot" field to the value that was provided on create.
func (u *SubmissionUpsert) UpdateTemplateFieldsSnapshot() *SubmissionUpsert {
	u.SetExcluded(submission.FieldTemplateFieldsSnapshot)
	return u
}

// ClearTemplateFieldsSnapshot clears the value of the "template_fields_snapshot" field.
func (u *SubmissionUpsert) ClearTemplateFieldsSnapshot() *SubmissionUpsert {
	u.SetNull(submission.FieldTemplateFieldsSnapshot)
	return u
}

// SetTemplateSchemaSnapshot sets the "template_schema_snapshot" field.
func (u *SubmissionUpsert) SetTemplateSchemaSnapshot(v map[string]interface{}) *SubmissionUpsert {
	u.Set(submission.FieldTemplateSchemaSnapshot, v)
	return u
}

// UpdateTemplateSchemaSnapshot sets the "template_schema_snapshot" field to the value that was provided on create.
func (u *SubmissionUpsert) UpdateTemplateSchemaSnapshot() *SubmissionUpsert {
	u.SetExcluded(submission.FieldTemplateSchemaSnapshot)
	return u
}

// ClearTemplateSchemaSnapshot clears the value of the "template_schema_snapshot" field.
func (u *SubmissionUpsert) ClearTemplateSchemaSnapshot() *SubmissionUpsert {
	u.SetNull(submission.FieldTemplateSchemaSnapshot)
	return u
}

// SetTemplateSubmittersSnapshot sets the "template_submitters_snapshot" field.
func (u *SubmissionUpsert) SetTemplateSubmittersSnapshot(v []map[string]interface{}) *SubmissionUpsert {
	u.Set(submission.FieldTemplateSubmittersSnapshot, v)
	return u
}

// UpdateTemplateSubmittersSnapshot sets the "template_submitters_snapshot" field to the value that was provided on create.
func (u *SubmissionUpsert) UpdateTemplateSubmittersSnapshot() *SubmissionUpsert {
	u.SetExcluded(submission.FieldTemplateSubmittersSnapshot)
	return u
}

// ClearTemplateSubmittersSnapshot clears the value of the "template_submitters_snapshot" field.
func (u *SubmissionUpsert) ClearTemplateSubmittersSnapshot() *SubmissionUpsert {
	u.SetNull(submission.FieldTemplateSubmittersSnapshot)
	return u
}

// SetPreferences sets the "preferences" field.
func (u *SubmissionUpsert) SetPreferences(v map[string]interface{}) *SubmissionUpsert {
	u.Set(submission.FieldPreferences, v)
	return u
}

// UpdatePreferences sets the "preferences" field to the value that was provided on create.
func (u *SubmissionUpsert) UpdatePreferences() *SubmissionUpsert {
	u.SetExcluded(submission.FieldPreferences)
	return u
}

// ClearPreferences clears the value of the "preferences" field.
func (u *SubmissionUpsert) ClearPreferences() *SubmissionUpsert {
	u.SetNull(submission.FieldPreferences)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *SubmissionUpsert) SetCompletedAt(v time.Time) *SubmissionUpsert {
	u.Set(submission.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *SubmissionUpsert) UpdateCompletedAt() *SubmissionUpsert {
	u.SetExcluded(submission.FieldCompletedAt)
	return u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *SubmissionUpsert) ClearCompletedAt() *SubmissionUpsert {
	u.SetNull(submission.FieldCompletedAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *SubmissionUpsert) SetExpiresAt(v time.Time) *SubmissionUpsert {
	u.Set(submission.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *SubmissionUpsert) UpdateExpiresAt() *SubmissionUpsert {
	u.SetExcluded(submission.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *SubmissionUpsert) ClearExpiresAt() *SubmissionUpsert {
	u.SetNull(submission.FieldExpiresAt)
	return u
}

// SetSource sets the "source" field.
func (u *SubmissionUpsert) SetSource(v string) *SubmissionUpsert {
	u.Set(submission.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *SubmissionUpsert) UpdateSource() *SubmissionUpsert {
	u.SetExcluded(submission.FieldSource)
	return u
}

// ClearSource clears the value of the "source" field.
func (u *SubmissionUpsert) ClearSource() *SubmissionUpsert {
	u.SetNull(submission.FieldSource)
	return u
}

// SetCurrentPdfKey sets the "current_pdf_key" field.
func (u *SubmissionUpsert) SetCurrentPdfKey(v string) *SubmissionUpsert {
	u.Set(submission.FieldCurrentPdfKey, v)
	return u
}

// UpdateCurrentPdfKey sets the "current_pdf_key" field to the value that was provided on create.
func (u *SubmissionUpsert) UpdateCurrentPdfKey() *SubmissionUpsert {
	u.SetExcluded(submission.FieldCurrentPdfKey)
	return u
}

// ClearCurrentPdfKey clears the value of the "current_pdf_key" field.
func (u *SubmissionUpsert) ClearCurrentPdfKey() *SubmissionUpsert {
	u.SetNull(submission.FieldCurrentPdfKey)
	return u
}

// SetSignedDocumentKey sets the "signed_document_key" field.
func (u *SubmissionUpsert) SetSignedDocumentKey(v string) *SubmissionUpsert {
	u.Set(submission.FieldSignedDocumentKey, v)
	return u
}

// UpdateSignedDocumentKey sets the "signed_document_key" field to the value that was provided on create.
func (u *SubmissionUpsert) UpdateSignedDocumentKey() *SubmissionUpsert {
	u.SetExcluded(submission.FieldSignedDocumentKey)
	return u
}

// ClearSignedDocumentKey clears the value of the "signed_document_key" field.
func (u *SubmissionUpsert) ClearSignedDocumentKey() *SubmissionUpsert {
	u.SetNull(submission.FieldSignedDocumentKey)
	return u
}

// SetAuditTrailKey sets the "audit_trail_key" field.
func (u *SubmissionUpsert) SetAuditTrailKey(v string) *SubmissionUpsert {
	u.Set(submission.FieldAuditTrailKey, v)
	return u
}

// UpdateAuditTrailKey sets the "audit_trail_key" field to the value that was provided on create.
func (u *SubmissionUpsert) UpdateAuditTrailKey() *SubmissionUpsert {
	u.SetExcluded(submission.FieldAuditTrailKey)
	return u
}

// ClearAuditTrailKey clears the value of the "audit_trail_key" field.
func (u *SubmissionUpsert) ClearAuditTrailKey() *SubmissionUpsert {
	u.SetNull(submission.FieldAuditTrailKey)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Submission.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(submission.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SubmissionUpsertOne) UpdateNewValues() *SubmissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(submission.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(submission.FieldCreateTime)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(submission.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Submission.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SubmissionUpsertOne) Ignore() *SubmissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubmissionUpsertOne) DoNothing() *SubmissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubmissionCreate.OnConflict
// documentation for more info.
func (u *SubmissionUpsertOne) Update(set func(*SubmissionUpsert)) *SubmissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubmissionUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *SubmissionUpsertOne) SetCreateBy(v uint32) *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *SubmissionUpsertOne) AddCreateBy(v uint32) *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *SubmissionUpsertOne) UpdateCreateBy() *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *SubmissionUpsertOne) ClearCreateBy() *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateBy sets the "update_by" field.
func (u *SubmissionUpsertOne) SetUpdateBy(v uint32) *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetUpdateBy(v)
	})
}

// AddUpdateBy adds v to the "update_by" field.
func (u *SubmissionUpsertOne) AddUpdateBy(v uint32) *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.AddUpdateBy(v)
	})
}

// UpdateUpdateBy sets the "update_by" field to the value that was provided on create.
func (u *SubmissionUpsertOne) UpdateUpdateBy() *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdateUpdateBy()
	})
}

// ClearUpdateBy clears the value of the "update_by" field.
func (u *SubmissionUpsertOne) ClearUpdateBy() *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.ClearUpdateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *SubmissionUpsertOne) SetUpdateTime(v time.Time) *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *SubmissionUpsertOne) UpdateUpdateTime() *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *SubmissionUpsertOne) ClearUpdateTime() *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *SubmissionUpsertOne) SetDeleteTime(v time.Time) *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *SubmissionUpsertOne) UpdateDeleteTime() *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *SubmissionUpsertOne) ClearDeleteTime() *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.ClearDeleteTime()
	})
}

// SetTemplateID sets the "template_id" field.
func (u *SubmissionUpsertOne) SetTemplateID(v string) *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetTemplateID(v)
	})
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *SubmissionUpsertOne) UpdateTemplateID() *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdateTemplateID()
	})
}

// SetSlug sets the "slug" field.
func (u *SubmissionUpsertOne) SetSlug(v string) *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *SubmissionUpsertOne) UpdateSlug() *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdateSlug()
	})
}

// SetSigningMode sets the "signing_mode" field.
func (u *SubmissionUpsertOne) SetSigningMode(v submission.SigningMode) *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetSigningMode(v)
	})
}

// UpdateSigningMode sets the "signing_mode" field to the value that was provided on create.
func (u *SubmissionUpsertOne) UpdateSigningMode() *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdateSigningMode()
	})
}

// SetStatus sets the "status" field.
func (u *SubmissionUpsertOne) SetStatus(v submission.Status) *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubmissionUpsertOne) UpdateStatus() *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdateStatus()
	})
}

// SetTemplateFieldsSnapshot sets the "template_fields_snapshot" field.
func (u *SubmissionUpsertOne) SetTemplateFieldsSnapshot(v []map[string]interface{}) *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetTemplateFieldsSnapshot(v)
	})
}

// UpdateTemplateFieldsSnapshot sets the "template_fields_snapshot" field to the value that was provided on create.
func (u *SubmissionUpsertOne) UpdateTemplateFieldsSnapshot() *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdateTemplateFieldsSnapshot()
	})
}

// ClearTemplateFieldsSnapshot clears the value of the "template_fields_snapshot" field.
func (u *SubmissionUpsertOne) ClearTemplateFieldsSnapshot() *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.ClearTemplateFieldsSnapshot()
	})
}

// SetTemplateSchemaSnapshot sets the "template_schema_snapshot" field.
func (u *SubmissionUpsertOne) SetTemplateSchemaSnapshot(v map[string]interface{}) *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetTemplateSchemaSnapshot(v)
	})
}

// UpdateTemplateSchemaSnapshot sets the "template_schema_snapshot" field to the value that was provided on create.
func (u *SubmissionUpsertOne) UpdateTemplateSchemaSnapshot() *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdateTemplateSchemaSnapshot()
	})
}

// ClearTemplateSchemaSnapshot clears the value of the "template_schema_snapshot" field.
func (u *SubmissionUpsertOne) ClearTemplateSchemaSnapshot() *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.ClearTemplateSchemaSnapshot()
	})
}

// SetTemplateSubmittersSnapshot sets the "template_submitters_snapshot" field.
func (u *SubmissionUpsertOne) SetTemplateSubmittersSnapshot(v []map[string]interface{}) *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetTemplateSubmittersSnapshot(v)
	})
}

// UpdateTemplateSubmittersSnapshot sets the "template_submitters_snapshot" field to the value that was provided on create.
func (u *SubmissionUpsertOne) UpdateTemplateSubmittersSnapshot() *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdateTemplateSubmittersSnapshot()
	})
}

// ClearTemplateSubmittersSnapshot clears the value of the "template_submitters_snapshot" field.
func (u *SubmissionUpsertOne) ClearTemplateSubmittersSnapshot() *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.ClearTemplateSubmittersSnapshot()
	})
}

// SetPreferences sets the "preferences" field.
func (u *SubmissionUpsertOne) SetPreferences(v map[string]interface{}) *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetPreferences(v)
	})
}

// UpdatePreferences sets the "preferences" field to the value that was provided on create.
func (u *SubmissionUpsertOne) UpdatePreferences() *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdatePreferences()
	})
}

// ClearPreferences clears the value of the "preferences" field.
func (u *SubmissionUpsertOne) ClearPreferences() *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.ClearPreferences()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *SubmissionUpsertOne) SetCompletedAt(v time.Time) *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *SubmissionUpsertOne) UpdateCompletedAt() *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *SubmissionUpsertOne) ClearCompletedAt() *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.ClearCompletedAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *SubmissionUpsertOne) SetExpiresAt(v time.Time) *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *SubmissionUpsertOne) UpdateExpiresAt() *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *SubmissionUpsertOne) ClearExpiresAt() *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.ClearExpiresAt()
	})
}

// SetSource sets the "source" field.
func (u *SubmissionUpsertOne) SetSource(v string) *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *SubmissionUpsertOne) UpdateSource() *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdateSource()
	})
}

// ClearSource clears the value of the "source" field.
func (u *SubmissionUpsertOne) ClearSource() *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.ClearSource()
	})
}

// SetCurrentPdfKey sets the "current_pdf_key" field.
func (u *SubmissionUpsertOne) SetCurrentPdfKey(v string) *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetCurrentPdfKey(v)
	})
}

// UpdateCurrentPdfKey sets the "current_pdf_key" field to the value that was provided on create.
func (u *SubmissionUpsertOne) UpdateCurrentPdfKey() *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdateCurrentPdfKey()
	})
}

// ClearCurrentPdfKey clears the value of the "current_pdf_key" field.
func (u *SubmissionUpsertOne) ClearCurrentPdfKey() *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.ClearCurrentPdfKey()
	})
}

// SetSignedDocumentKey sets the "signed_document_key" field.
func (u *SubmissionUpsertOne) SetSignedDocumentKey(v string) *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetSignedDocumentKey(v)
	})
}

// UpdateSignedDocumentKey sets the "signed_document_key" field to the value that was provided on create.
func (u *SubmissionUpsertOne) UpdateSignedDocumentKey() *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdateSignedDocumentKey()
	})
}

// ClearSignedDocumentKey clears the value of the "signed_document_key" field.
func (u *SubmissionUpsertOne) ClearSignedDocumentKey() *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.ClearSignedDocumentKey()
	})
}

// SetAuditTrailKey sets the "audit_trail_key" field.
func (u *SubmissionUpsertOne) SetAuditTrailKey(v string) *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetAuditTrailKey(v)
	})
}

// UpdateAuditTrailKey sets the "audit_trail_key" field to the value that was provided on create.
func (u *SubmissionUpsertOne) UpdateAuditTrailKey() *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdateAuditTrailKey()
	})
}

// ClearAuditTrailKey clears the value of the "audit_trail_key" field.
func (u *SubmissionUpsertOne) ClearAuditTrailKey() *SubmissionUpsertOne {
	return u.Update(func(s *SubmissionUpsert) {
		s.ClearAuditTrailKey()
	})
}

// Exec executes the query.
func (u *SubmissionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubmissionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubmissionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SubmissionUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: SubmissionUpsertOne.ID is not supported by MySQL driver. Use SubmissionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SubmissionUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SubmissionCreateBulk is the builder for creating many Submission entities in bulk.
type SubmissionCreateBulk struct {
	config
	err      error
	builders []*SubmissionCreate
	conflict []sql.ConflictOption
}

// Save creates the Submission entities in the database.
func (_c *SubmissionCreateBulk) Save(ctx context.Context) ([]*Submission, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Submission, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubmissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubmissionCreateBulk) SaveX(ctx context.Context) []*Submission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubmissionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubmissionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Submission.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubmissionUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *SubmissionCreateBulk) OnConflict(opts ...sql.ConflictOption) *SubmissionUpsertBulk {
	_c.conflict = opts
	return &SubmissionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Submission.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubmissionCreateBulk) OnConflictColumns(columns ...string) *SubmissionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubmissionUpsertBulk{
		create: _c,
	}
}

// SubmissionUpsertBulk is the builder for "upsert"-ing
// a bulk of Submission nodes.
type SubmissionUpsertBulk struct {
	create *SubmissionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Submission.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(submission.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SubmissionUpsertBulk) UpdateNewValues() *SubmissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(submission.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(submission.FieldCreateTime)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(submission.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Submission.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SubmissionUpsertBulk) Ignore() *SubmissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubmissionUpsertBulk) DoNothing() *SubmissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubmissionCreateBulk.OnConflict
// documentation for more info.
func (u *SubmissionUpsertBulk) Update(set func(*SubmissionUpsert)) *SubmissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubmissionUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *SubmissionUpsertBulk) SetCreateBy(v uint32) *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *SubmissionUpsertBulk) AddCreateBy(v uint32) *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *SubmissionUpsertBulk) UpdateCreateBy() *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *SubmissionUpsertBulk) ClearCreateBy() *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateBy sets the "update_by" field.
func (u *SubmissionUpsertBulk) SetUpdateBy(v uint32) *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetUpdateBy(v)
	})
}

// AddUpdateBy adds v to the "update_by" field.
func (u *SubmissionUpsertBulk) AddUpdateBy(v uint32) *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.AddUpdateBy(v)
	})
}

// UpdateUpdateBy sets the "update_by" field to the value that was provided on create.
func (u *SubmissionUpsertBulk) UpdateUpdateBy() *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdateUpdateBy()
	})
}

// ClearUpdateBy clears the value of the "update_by" field.
func (u *SubmissionUpsertBulk) ClearUpdateBy() *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.ClearUpdateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *SubmissionUpsertBulk) SetUpdateTime(v time.Time) *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *SubmissionUpsertBulk) UpdateUpdateTime() *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *SubmissionUpsertBulk) ClearUpdateTime() *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *SubmissionUpsertBulk) SetDeleteTime(v time.Time) *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *SubmissionUpsertBulk) UpdateDeleteTime() *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *SubmissionUpsertBulk) ClearDeleteTime() *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.ClearDeleteTime()
	})
}

// SetTemplateID sets the "template_id" field.
func (u *SubmissionUpsertBulk) SetTemplateID(v string) *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetTemplateID(v)
	})
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *SubmissionUpsertBulk) UpdateTemplateID() *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdateTemplateID()
	})
}

// SetSlug sets the "slug" field.
func (u *SubmissionUpsertBulk) SetSlug(v string) *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *SubmissionUpsertBulk) UpdateSlug() *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdateSlug()
	})
}

// SetSigningMode sets the "signing_mode" field.
func (u *SubmissionUpsertBulk) SetSigningMode(v submission.SigningMode) *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetSigningMode(v)
	})
}

// UpdateSigningMode sets the "signing_mode" field to the value that was provided on create.
func (u *SubmissionUpsertBulk) UpdateSigningMode() *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdateSigningMode()
	})
}

// SetStatus sets the "status" field.
func (u *SubmissionUpsertBulk) SetStatus(v submission.Status) *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubmissionUpsertBulk) UpdateStatus() *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdateStatus()
	})
}

// SetTemplateFieldsSnapshot sets the "template_fields_snapshot" field.
func (u *SubmissionUpsertBulk) SetTemplateFieldsSnapshot(v []map[string]interface{}) *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetTemplateFieldsSnapshot(v)
	})
}

// UpdateTemplateFieldsSnapshot sets the "template_fields_snapshot" field to the value that was provided on create.
func (u *SubmissionUpsertBulk) UpdateTemplateFieldsSnapshot() *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdateTemplateFieldsSnapshot()
	})
}

// ClearTemplateFieldsSnapshot clears the value of the "template_fields_snapshot" field.
func (u *SubmissionUpsertBulk) ClearTemplateFieldsSnapshot() *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.ClearTemplateFieldsSnapshot()
	})
}

// SetTemplateSchemaSnapshot sets the "template_schema_snapshot" field.
func (u *SubmissionUpsertBulk) SetTemplateSchemaSnapshot(v map[string]interface{}) *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetTemplateSchemaSnapshot(v)
	})
}

// UpdateTemplateSchemaSnapshot sets the "template_schema_snapshot" field to the value that was provided on create.
func (u *SubmissionUpsertBulk) UpdateTemplateSchemaSnapshot() *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdateTemplateSchemaSnapshot()
	})
}

// ClearTemplateSchemaSnapshot clears the value of the "template_schema_snapshot" field.
func (u *SubmissionUpsertBulk) ClearTemplateSchemaSnapshot() *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.ClearTemplateSchemaSnapshot()
	})
}

// SetTemplateSubmittersSnapshot sets the "template_submitters_snapshot" field.
func (u *SubmissionUpsertBulk) SetTemplateSubmittersSnapshot(v []map[string]interface{}) *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetTemplateSubmittersSnapshot(v)
	})
}

// UpdateTemplateSubmittersSnapshot sets the "template_submitters_snapshot" field to the value that was provided on create.
func (u *SubmissionUpsertBulk) UpdateTemplateSubmittersSnapshot() *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdateTemplateSubmittersSnapshot()
	})
}

// ClearTemplateSubmittersSnapshot clears the value of the "template_submitters_snapshot" field.
func (u *SubmissionUpsertBulk) ClearTemplateSubmittersSnapshot() *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.ClearTemplateSubmittersSnapshot()
	})
}

// SetPreferences sets the "preferences" field.
func (u *SubmissionUpsertBulk) SetPreferences(v map[string]interface{}) *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetPreferences(v)
	})
}

// UpdatePreferences sets the "preferences" field to the value that was provided on create.
func (u *SubmissionUpsertBulk) UpdatePreferences() *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdatePreferences()
	})
}

// ClearPreferences clears the value of the "preferences" field.
func (u *SubmissionUpsertBulk) ClearPreferences() *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.ClearPreferences()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *SubmissionUpsertBulk) SetCompletedAt(v time.Time) *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *SubmissionUpsertBulk) UpdateCompletedAt() *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *SubmissionUpsertBulk) ClearCompletedAt() *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.ClearCompletedAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *SubmissionUpsertBulk) SetExpiresAt(v time.Time) *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *SubmissionUpsertBulk) UpdateExpiresAt() *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *SubmissionUpsertBulk) ClearExpiresAt() *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.ClearExpiresAt()
	})
}

// SetSource sets the "source" field.
func (u *SubmissionUpsertBulk) SetSource(v string) *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *SubmissionUpsertBulk) UpdateSource() *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdateSource()
	})
}

// ClearSource clears the value of the "source" field.
func (u *SubmissionUpsertBulk) ClearSource() *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.ClearSource()
	})
}

// SetCurrentPdfKey sets the "current_pdf_key" field.
func (u *SubmissionUpsertBulk) SetCurrentPdfKey(v string) *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetCurrentPdfKey(v)
	})
}

// UpdateCurrentPdfKey sets the "current_pdf_key" field to the value that was provided on create.
func (u *SubmissionUpsertBulk) UpdateCurrentPdfKey() *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdateCurrentPdfKey()
	})
}

// ClearCurrentPdfKey clears the value of the "current_pdf_key" field.
func (u *SubmissionUpsertBulk) ClearCurrentPdfKey() *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.ClearCurrentPdfKey()
	})
}

// SetSignedDocumentKey sets the "signed_document_key" field.
func (u *SubmissionUpsertBulk) SetSignedDocumentKey(v string) *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetSignedDocumentKey(v)
	})
}

// UpdateSignedDocumentKey sets the "signed_document_key" field to the value that was provided on create.
func (u *SubmissionUpsertBulk) UpdateSignedDocumentKey() *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdateSignedDocumentKey()
	})
}

// ClearSignedDocumentKey clears the value of the "signed_document_key" field.
func (u *SubmissionUpsertBulk) ClearSignedDocumentKey() *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.ClearSignedDocumentKey()
	})
}

// SetAuditTrailKey sets the "audit_trail_key" field.
func (u *SubmissionUpsertBulk) SetAuditTrailKey(v string) *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.SetAuditTrailKey(v)
	})
}

// UpdateAuditTrailKey sets the "audit_trail_key" field to the value that was provided on create.
func (u *SubmissionUpsertBulk) UpdateAuditTrailKey() *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.UpdateAuditTrailKey()
	})
}

// ClearAuditTrailKey clears the value of the "audit_trail_key" field.
func (u *SubmissionUpsertBulk) ClearAuditTrailKey() *SubmissionUpsertBulk {
	return u.Update(func(s *SubmissionUpsert) {
		s.ClearAuditTrailKey()
	})
}

// Exec executes the query.
func (u *SubmissionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SubmissionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubmissionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubmissionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
