// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-signing/internal/data/ent/submission"
	"github.com/go-tangra/go-tangra-signing/internal/data/ent/submitter"
)

// Submitter is the model entity for the Submitter schema.
type Submitter struct {
	config `json:"-"`
	// ID of the ent.
	// UUID primary key
	ID string `json:"id,omitempty"`
	// 创建时间
	CreateTime *time.Time `json:"create_time,omitempty"`
	// 更新时间
	UpdateTime *time.Time `json:"update_time,omitempty"`
	// 删除时间
	DeleteTime *time.Time `json:"delete_time,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// Parent submission ID
	SubmissionID string `json:"submission_id,omitempty"`
	// Signer display name
	Name string `json:"name,omitempty"`
	// Signer email for notifications
	Email string `json:"email,omitempty"`
	// Signer phone for SMS
	Phone string `json:"phone,omitempty"`
	// Unique slug for signing link
	Slug string `json:"slug,omitempty"`
	// Order in sequential signing (0-based)
	SigningOrder int `json:"signing_order,omitempty"`
	// Role label (e.g. Buyer, Seller, Witness)
	Role string `json:"role,omitempty"`
	// Submitter signing status
	Status submitter.Status `json:"status,omitempty"`
	// Filled form field values
	Values map[string]interface{} `json:"values,omitempty"`
	// Additional metadata: template_submitter_id, etc.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// IP address of signer
	IP string `json:"ip,omitempty"`
	// User agent of signer
	UserAgent string `json:"user_agent,omitempty"`
	// Reason for declining
	DeclineReason string `json:"decline_reason,omitempty"`
	// When invitation was sent
	SentAt *time.Time `json:"sent_at,omitempty"`
	// When signer opened the link
	OpenedAt *time.Time `json:"opened_at,omitempty"`
	// When signer completed signing
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SubmitterQuery when eager-loading is set.
	Edges        SubmitterEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SubmitterEdges holds the relations/edges for other nodes in the graph.
type SubmitterEdges struct {
	// Parent submission
	Submission *Submission `json:"submission,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SubmissionOrErr returns the Submission value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubmitterEdges) SubmissionOrErr() (*Submission, error) {
	if e.Submission != nil {
		return e.Submission, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: submission.Label}
	}
	return nil, &NotLoadedError{edge: "submission"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Submitter) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case submitter.FieldValues, submitter.FieldMetadata:
			values[i] = new([]byte)
		case submitter.FieldTenantID, submitter.FieldSigningOrder:
			values[i] = new(sql.NullInt64)
		case submitter.FieldID, submitter.FieldSubmissionID, submitter.FieldName, submitter.FieldEmail, submitter.FieldPhone, submitter.FieldSlug, submitter.FieldRole, submitter.FieldStatus, submitter.FieldIP, submitter.FieldUserAgent, submitter.FieldDeclineReason:
			values[i] = new(sql.NullString)
		case submitter.FieldCreateTime, submitter.FieldUpdateTime, submitter.FieldDeleteTime, submitter.FieldSentAt, submitter.FieldOpenedAt, submitter.FieldCompletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Submitter fields.
func (_m *Submitter) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case submitter.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case submitter.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = new(time.Time)
				*_m.CreateTime = value.Time
			}
		case submitter.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = new(time.Time)
				*_m.UpdateTime = value.Time
			}
		case submitter.FieldDeleteTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field delete_time", values[i])
			} else if value.Valid {
				_m.DeleteTime = new(time.Time)
				*_m.DeleteTime = value.Time
			}
		case submitter.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case submitter.FieldSubmissionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field submission_id", values[i])
			} else if value.Valid {
				_m.SubmissionID = value.String
			}
		case submitter.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case submitter.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case submitter.FieldPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phone", values[i])
			} else if value.Valid {
				_m.Phone = value.String
			}
		case submitter.FieldSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field slug", values[i])
			} else if value.Valid {
				_m.Slug = value.String
			}
		case submitter.FieldSigningOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field signing_order", values[i])
			} else if value.Valid {
				_m.SigningOrder = int(value.Int64)
			}
		case submitter.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = value.String
			}
		case submitter.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = submitter.Status(value.String)
			}
		case submitter.FieldValues:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field values", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Values); err != nil {
					return fmt.Errorf("unmarshal field values: %w", err)
				}
			}
		case submitter.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case submitter.FieldIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip", values[i])
			} else if value.Valid {
				_m.IP = value.String
			}
		case submitter.FieldUserAgent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_agent", values[i])
			} else if value.Valid {
				_m.UserAgent = value.String
			}
		case submitter.FieldDeclineReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field decline_reason", values[i])
			} else if value.Valid {
				_m.DeclineReason = value.String
			}
		case submitter.FieldSentAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field sent_at", values[i])
			} else if value.Valid {
				_m.SentAt = new(time.Time)
				*_m.SentAt = value.Time
			}
		case submitter.FieldOpenedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field opened_at", values[i])
			} else if value.Valid {
				_m.OpenedAt = new(time.Time)
				*_m.OpenedAt = value.Time
			}
		case submitter.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Submitter.
// This includes values selected through modifiers, order, etc.
func (_m *Submitter) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySubmission queries the "submission" edge of the Submitter entity.
func (_m *Submitter) QuerySubmission() *SubmissionQuery {
	return NewSubmitterClient(_m.config).QuerySubmission(_m)
}

// Update returns a builder for updating this Submitter.
// Note that you need to call Submitter.Unwrap() before calling this method if this Submitter
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Submitter) Update() *SubmitterUpdateOne {
	return NewSubmitterClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Submitter entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Submitter) Unwrap() *Submitter {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Submitter is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Submitter) String() string {
	var builder strings.Builder
	builder.WriteString("Submitter(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreateTime; v != nil {
		builder.WriteString("create_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdateTime; v != nil {
		builder.WriteString("update_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeleteTime; v != nil {
		builder.WriteString("delete_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("submission_id=")
	builder.WriteString(_m.SubmissionID)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("phone=")
	builder.WriteString(_m.Phone)
	builder.WriteString(", ")
	builder.WriteString("slug=")
	builder.WriteString(_m.Slug)
	builder.WriteString(", ")
	builder.WriteString("signing_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SigningOrder))
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(_m.Role)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("values=")
	builder.WriteString(fmt.Sprintf("%v", _m.Values))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("ip=")
	builder.WriteString(_m.IP)
	builder.WriteString(", ")
	builder.WriteString("user_agent=")
	builder.WriteString(_m.UserAgent)
	builder.WriteString(", ")
	builder.WriteString("decline_reason=")
	builder.WriteString(_m.DeclineReason)
	builder.WriteString(", ")
	if v := _m.SentAt; v != nil {
		builder.WriteString("sent_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.OpenedAt; v != nil {
		builder.WriteString("opened_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Submitters is a parsable slice of Submitter.
type Submitters []*Submitter
