// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-signing/internal/data/ent/submission"
	"github.com/go-tangra/go-tangra-signing/internal/data/ent/template"
)

// Submission is the model entity for the Submission schema.
type Submission struct {
	config `json:"-"`
	// ID of the ent.
	// UUID primary key
	ID string `json:"id,omitempty"`
	// 创建者ID
	CreateBy *uint32 `json:"create_by,omitempty"`
	// 更新者ID
	UpdateBy *uint32 `json:"update_by,omitempty"`
	// 创建时间
	CreateTime *time.Time `json:"create_time,omitempty"`
	// 更新时间
	UpdateTime *time.Time `json:"update_time,omitempty"`
	// 删除时间
	DeleteTime *time.Time `json:"delete_time,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// Source template ID
	TemplateID string `json:"template_id,omitempty"`
	// URL-friendly unique identifier
	Slug string `json:"slug,omitempty"`
	// Sequential (one-by-one) or parallel (all at once)
	SigningMode submission.SigningMode `json:"signing_mode,omitempty"`
	// Submission lifecycle status
	Status submission.Status `json:"status,omitempty"`
	// Snapshot of template fields at creation time
	TemplateFieldsSnapshot []map[string]interface{} `json:"template_fields_snapshot,omitempty"`
	// Snapshot of template schema at creation time
	TemplateSchemaSnapshot map[string]interface{} `json:"template_schema_snapshot,omitempty"`
	// Snapshot of template submitters at creation time
	TemplateSubmittersSnapshot []map[string]interface{} `json:"template_submitters_snapshot,omitempty"`
	// Submission preferences: reminders, expiration, locale
	Preferences map[string]interface{} `json:"preferences,omitempty"`
	// When all signers completed
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// Submission expiration deadline
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// Source: direct_link, form_based, api, bulk
	Source string `json:"source,omitempty"`
	// Storage key for the in-progress PDF with completed signers' data overlaid
	CurrentPdfKey string `json:"current_pdf_key,omitempty"`
	// Storage key for the final signed PDF
	SignedDocumentKey string `json:"signed_document_key,omitempty"`
	// Storage key for the audit trail PDF
	AuditTrailKey string `json:"audit_trail_key,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SubmissionQuery when eager-loading is set.
	Edges        SubmissionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SubmissionEdges holds the relations/edges for other nodes in the graph.
type SubmissionEdges struct {
	// Source template
	Template *Template `json:"template,omitempty"`
	// Signers for this submission
	Submitters []*Submitter `json:"submitters,omitempty"`
	// Events for this submission
	Events []*Event `json:"events,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// TemplateOrErr returns the Template value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubmissionEdges) TemplateOrErr() (*Template, error) {
	if e.Template != nil {
		return e.Template, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: template.Label}
	}
	return nil, &NotLoadedError{edge: "template"}
}

// SubmittersOrErr returns the Submitters value or an error if the edge
// was not loaded in eager-loading.
func (e SubmissionEdges) SubmittersOrErr() ([]*Submitter, error) {
	if e.loadedTypes[1] {
		return e.Submitters, nil
	}
	return nil, &NotLoadedError{edge: "submitters"}
}

// EventsOrErr returns the Events value or an error if the edge
// was not loaded in eager-loading.
func (e SubmissionEdges) EventsOrErr() ([]*Event, error) {
	if e.loadedTypes[2] {
		return e.Events, nil
	}
	return nil, &NotLoadedError{edge: "events"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Submission) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case submission.FieldTemplateFieldsSnapshot, submission.FieldTemplateSchemaSnapshot, submission.FieldTemplateSubmittersSnapshot, submission.FieldPreferences:
			values[i] = new([]byte)
		case submission.FieldCreateBy, submission.FieldUpdateBy, submission.FieldTenantID:
			values[i] = new(sql.NullInt64)
		case submission.FieldID, submission.FieldTemplateID, submission.FieldSlug, submission.FieldSigningMode, submission.FieldStatus, submission.FieldSource, submission.FieldCurrentPdfKey, submission.FieldSignedDocumentKey, submission.FieldAuditTrailKey:
			values[i] = new(sql.NullString)
		case submission.FieldCreateTime, submission.FieldUpdateTime, submission.FieldDeleteTime, submission.FieldCompletedAt, submission.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Submission fields.
func (_m *Submission) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case submission.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case submission.FieldCreateBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field create_by", values[i])
			} else if value.Valid {
				_m.CreateBy = new(uint32)
				*_m.CreateBy = uint32(value.Int64)
			}
		case submission.FieldUpdateBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field update_by", values[i])
			} else if value.Valid {
				_m.UpdateBy = new(uint32)
				*_m.UpdateBy = uint32(value.Int64)
			}
		case submission.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = new(time.Time)
				*_m.CreateTime = value.Time
			}
		case submission.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = new(time.Time)
				*_m.UpdateTime = value.Time
			}
		case submission.FieldDeleteTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field delete_time", values[i])
			} else if value.Valid {
				_m.DeleteTime = new(time.Time)
				*_m.DeleteTime = value.Time
			}
		case submission.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case submission.FieldTemplateID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field template_id", values[i])
			} else if value.Valid {
				_m.TemplateID = value.String
			}
		case submission.FieldSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field slug", values[i])
			} else if value.Valid {
				_m.Slug = value.String
			}
		case submission.FieldSigningMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field signing_mode", values[i])
			} else if value.Valid {
				_m.SigningMode = submission.SigningMode(value.String)
			}
		case submission.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = submission.Status(value.String)
			}
		case submission.FieldTemplateFieldsSnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field template_fields_snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.TemplateFieldsSnapshot); err != nil {
					return fmt.Errorf("unmarshal field template_fields_snapshot: %w", err)
				}
			}
		case submission.FieldTemplateSchemaSnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field template_schema_snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.TemplateSchemaSnapshot); err != nil {
					return fmt.Errorf("unmarshal field template_schema_snapshot: %w", err)
				}
			}
		case submission.FieldTemplateSubmittersSnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field template_submitters_snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.TemplateSubmittersSnapshot); err != nil {
					return fmt.Errorf("unmarshal field template_submitters_snapshot: %w", err)
				}
			}
		case submission.FieldPreferences:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field preferences", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Preferences); err != nil {
					return fmt.Errorf("unmarshal field preferences: %w", err)
				}
			}
		case submission.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		case submission.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case submission.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case submission.FieldCurrentPdfKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field current_pdf_key", values[i])
			} else if value.Valid {
				_m.CurrentPdfKey = value.String
			}
		case submission.FieldSignedDocumentKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field signed_document_key", values[i])
			} else if value.Valid {
				_m.SignedDocumentKey = value.String
			}
		case submission.FieldAuditTrailKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field audit_trail_key", values[i])
			} else if value.Valid {
				_m.AuditTrailKey = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Submission.
// This includes values selected through modifiers, order, etc.
func (_m *Submission) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTemplate queries the "template" edge of the Submission entity.
func (_m *Submission) QueryTemplate() *TemplateQuery {
	return NewSubmissionClient(_m.config).QueryTemplate(_m)
}

// QuerySubmitters queries the "submitters" edge of the Submission entity.
func (_m *Submission) QuerySubmitters() *SubmitterQuery {
	return NewSubmissionClient(_m.config).QuerySubmitters(_m)
}

// QueryEvents queries the "events" edge of the Submission entity.
func (_m *Submission) QueryEvents() *EventQuery {
	return NewSubmissionClient(_m.config).QueryEvents(_m)
}

// Update returns a builder for updating this Submission.
// Note that you need to call Submission.Unwrap() before calling this method if this Submission
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Submission) Update() *SubmissionUpdateOne {
	return NewSubmissionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Submission entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Submission) Unwrap() *Submission {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Submission is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Submission) String() string {
	var builder strings.Builder
	builder.WriteString("Submission(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreateBy; v != nil {
		builder.WriteString("create_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdateBy; v != nil {
		builder.WriteString("update_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CreateTime; v != nil {
		builder.WriteString("create_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdateTime; v != nil {
		builder.WriteString("update_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeleteTime; v != nil {
		builder.WriteString("delete_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("template_id=")
	builder.WriteString(_m.TemplateID)
	builder.WriteString(", ")
	builder.WriteString("slug=")
	builder.WriteString(_m.Slug)
	builder.WriteString(", ")
	builder.WriteString("signing_mode=")
	builder.WriteString(fmt.Sprintf("%v", _m.SigningMode))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("template_fields_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.TemplateFieldsSnapshot))
	builder.WriteString(", ")
	builder.WriteString("template_schema_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.TemplateSchemaSnapshot))
	builder.WriteString(", ")
	builder.WriteString("template_submitters_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.TemplateSubmittersSnapshot))
	builder.WriteString(", ")
	builder.WriteString("preferences=")
	builder.WriteString(fmt.Sprintf("%v", _m.Preferences))
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("current_pdf_key=")
	builder.WriteString(_m.CurrentPdfKey)
	builder.WriteString(", ")
	builder.WriteString("signed_document_key=")
	builder.WriteString(_m.SignedDocumentKey)
	builder.WriteString(", ")
	builder.WriteString("audit_trail_key=")
	builder.WriteString(_m.AuditTrailKey)
	builder.WriteByte(')')
	return builder.String()
}

// Submissions is a parsable slice of Submission.
type Submissions []*Submission
