// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-signing/internal/data/ent/predicate"
	"github.com/go-tangra/go-tangra-signing/internal/data/ent/template"
	"github.com/go-tangra/go-tangra-signing/internal/data/ent/templatefolder"
)

// TemplateFolderUpdate is the builder for updating TemplateFolder entities.
type TemplateFolderUpdate struct {
	config
	hooks     []Hook
	mutation  *TemplateFolderMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the TemplateFolderUpdate builder.
func (_u *TemplateFolderUpdate) Where(ps ...predicate.TemplateFolder) *TemplateFolderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreateBy sets the "create_by" field.
func (_u *TemplateFolderUpdate) SetCreateBy(v uint32) *TemplateFolderUpdate {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *TemplateFolderUpdate) SetNillableCreateBy(v *uint32) *TemplateFolderUpdate {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *TemplateFolderUpdate) AddCreateBy(v int32) *TemplateFolderUpdate {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *TemplateFolderUpdate) ClearCreateBy() *TemplateFolderUpdate {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *TemplateFolderUpdate) SetUpdateTime(v time.Time) *TemplateFolderUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *TemplateFolderUpdate) SetNillableUpdateTime(v *time.Time) *TemplateFolderUpdate {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *TemplateFolderUpdate) ClearUpdateTime() *TemplateFolderUpdate {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *TemplateFolderUpdate) SetDeleteTime(v time.Time) *TemplateFolderUpdate {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *TemplateFolderUpdate) SetNillableDeleteTime(v *time.Time) *TemplateFolderUpdate {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *TemplateFolderUpdate) ClearDeleteTime() *TemplateFolderUpdate {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *TemplateFolderUpdate) SetParentID(v string) *TemplateFolderUpdate {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *TemplateFolderUpdate) SetNillableParentID(v *string) *TemplateFolderUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *TemplateFolderUpdate) ClearParentID() *TemplateFolderUpdate {
	_u.mutation.ClearParentID()
	return _u
}

// SetName sets the "name" field.
func (_u *TemplateFolderUpdate) SetName(v string) *TemplateFolderUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TemplateFolderUpdate) SetNillableName(v *string) *TemplateFolderUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *TemplateFolderUpdate) SetPath(v string) *TemplateFolderUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *TemplateFolderUpdate) SetNillablePath(v *string) *TemplateFolderUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// ClearPath clears the value of the "path" field.
func (_u *TemplateFolderUpdate) ClearPath() *TemplateFolderUpdate {
	_u.mutation.ClearPath()
	return _u
}

// SetDepth sets the "depth" field.
func (_u *TemplateFolderUpdate) SetDepth(v int) *TemplateFolderUpdate {
	_u.mutation.ResetDepth()
	_u.mutation.SetDepth(v)
	return _u
}

// SetNillableDepth sets the "depth" field if the given value is not nil.
func (_u *TemplateFolderUpdate) SetNillableDepth(v *int) *TemplateFolderUpdate {
	if v != nil {
		_u.SetDepth(*v)
	}
	return _u
}

// AddDepth adds value to the "depth" field.
func (_u *TemplateFolderUpdate) AddDepth(v int) *TemplateFolderUpdate {
	_u.mutation.AddDepth(v)
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *TemplateFolderUpdate) SetSortOrder(v int) *TemplateFolderUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *TemplateFolderUpdate) SetNillableSortOrder(v *int) *TemplateFolderUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *TemplateFolderUpdate) AddSortOrder(v int) *TemplateFolderUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// AddTemplateIDs adds the "templates" edge to the Template entity by IDs.
func (_u *TemplateFolderUpdate) AddTemplateIDs(ids ...string) *TemplateFolderUpdate {
	_u.mutation.AddTemplateIDs(ids...)
	return _u
}

// AddTemplates adds the "templates" edges to the Template entity.
func (_u *TemplateFolderUpdate) AddTemplates(v ...*Template) *TemplateFolderUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTemplateIDs(ids...)
}

// SetParent sets the "parent" edge to the TemplateFolder entity.
func (_u *TemplateFolderUpdate) SetParent(v *TemplateFolder) *TemplateFolderUpdate {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the TemplateFolder entity by IDs.
func (_u *TemplateFolderUpdate) AddChildIDs(ids ...string) *TemplateFolderUpdate {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the TemplateFolder entity.
func (_u *TemplateFolderUpdate) AddChildren(v ...*TemplateFolder) *TemplateFolderUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// Mutation returns the TemplateFolderMutation object of the builder.
func (_u *TemplateFolderUpdate) Mutation() *TemplateFolderMutation {
	return _u.mutation
}

// ClearTemplates clears all "templates" edges to the Template entity.
func (_u *TemplateFolderUpdate) ClearTemplates() *TemplateFolderUpdate {
	_u.mutation.ClearTemplates()
	return _u
}

// RemoveTemplateIDs removes the "templates" edge to Template entities by IDs.
func (_u *TemplateFolderUpdate) RemoveTemplateIDs(ids ...string) *TemplateFolderUpdate {
	_u.mutation.RemoveTemplateIDs(ids...)
	return _u
}

// RemoveTemplates removes "templates" edges to Template entities.
func (_u *TemplateFolderUpdate) RemoveTemplates(v ...*Template) *TemplateFolderUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTemplateIDs(ids...)
}

// ClearParent clears the "parent" edge to the TemplateFolder entity.
func (_u *TemplateFolderUpdate) ClearParent() *TemplateFolderUpdate {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the TemplateFolder entity.
func (_u *TemplateFolderUpdate) ClearChildren() *TemplateFolderUpdate {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to TemplateFolder entities by IDs.
func (_u *TemplateFolderUpdate) RemoveChildIDs(ids ...string) *TemplateFolderUpdate {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to TemplateFolder entities.
func (_u *TemplateFolderUpdate) RemoveChildren(v ...*TemplateFolder) *TemplateFolderUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TemplateFolderUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TemplateFolderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TemplateFolderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TemplateFolderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TemplateFolderUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := templatefolder.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TemplateFolder.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := templatefolder.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "TemplateFolder.path": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TemplateFolderUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TemplateFolderUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TemplateFolderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(templatefolder.Table, templatefolder.Columns, sqlgraph.NewFieldSpec(templatefolder.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(templatefolder.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(templatefolder.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(templatefolder.FieldCreateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(templatefolder.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(templatefolder.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(templatefolder.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(templatefolder.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(templatefolder.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(templatefolder.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(templatefolder.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(templatefolder.FieldPath, field.TypeString, value)
	}
	if _u.mutation.PathCleared() {
		_spec.ClearField(templatefolder.FieldPath, field.TypeString)
	}
	if value, ok := _u.mutation.Depth(); ok {
		_spec.SetField(templatefolder.FieldDepth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDepth(); ok {
		_spec.AddField(templatefolder.FieldDepth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(templatefolder.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(templatefolder.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.TemplatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   templatefolder.TemplatesTable,
			Columns: []string{templatefolder.TemplatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(template.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTemplatesIDs(); len(nodes) > 0 && !_u.mutation.TemplatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   templatefolder.TemplatesTable,
			Columns: []string{templatefolder.TemplatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(template.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TemplatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   templatefolder.TemplatesTable,
			Columns: []string{templatefolder.TemplatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(template.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   templatefolder.ParentTable,
			Columns: []string{templatefolder.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(templatefolder.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   templatefolder.ParentTable,
			Columns: []string{templatefolder.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(templatefolder.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   templatefolder.ChildrenTable,
			Columns: []string{templatefolder.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(templatefolder.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   templatefolder.ChildrenTable,
			Columns: []string{templatefolder.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(templatefolder.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   templatefolder.ChildrenTable,
			Columns: []string{templatefolder.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(templatefolder.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{templatefolder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TemplateFolderUpdateOne is the builder for updating a single TemplateFolder entity.
type TemplateFolderUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *TemplateFolderMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreateBy sets the "create_by" field.
func (_u *TemplateFolderUpdateOne) SetCreateBy(v uint32) *TemplateFolderUpdateOne {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *TemplateFolderUpdateOne) SetNillableCreateBy(v *uint32) *TemplateFolderUpdateOne {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *TemplateFolderUpdateOne) AddCreateBy(v int32) *TemplateFolderUpdateOne {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *TemplateFolderUpdateOne) ClearCreateBy() *TemplateFolderUpdateOne {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *TemplateFolderUpdateOne) SetUpdateTime(v time.Time) *TemplateFolderUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *TemplateFolderUpdateOne) SetNillableUpdateTime(v *time.Time) *TemplateFolderUpdateOne {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *TemplateFolderUpdateOne) ClearUpdateTime() *TemplateFolderUpdateOne {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *TemplateFolderUpdateOne) SetDeleteTime(v time.Time) *TemplateFolderUpdateOne {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *TemplateFolderUpdateOne) SetNillableDeleteTime(v *time.Time) *TemplateFolderUpdateOne {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *TemplateFolderUpdateOne) ClearDeleteTime() *TemplateFolderUpdateOne {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *TemplateFolderUpdateOne) SetParentID(v string) *TemplateFolderUpdateOne {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *TemplateFolderUpdateOne) SetNillableParentID(v *string) *TemplateFolderUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *TemplateFolderUpdateOne) ClearParentID() *TemplateFolderUpdateOne {
	_u.mutation.ClearParentID()
	return _u
}

// SetName sets the "name" field.
func (_u *TemplateFolderUpdateOne) SetName(v string) *TemplateFolderUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TemplateFolderUpdateOne) SetNillableName(v *string) *TemplateFolderUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *TemplateFolderUpdateOne) SetPath(v string) *TemplateFolderUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *TemplateFolderUpdateOne) SetNillablePath(v *string) *TemplateFolderUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// ClearPath clears the value of the "path" field.
func (_u *TemplateFolderUpdateOne) ClearPath() *TemplateFolderUpdateOne {
	_u.mutation.ClearPath()
	return _u
}

// SetDepth sets the "depth" field.
func (_u *TemplateFolderUpdateOne) SetDepth(v int) *TemplateFolderUpdateOne {
	_u.mutation.ResetDepth()
	_u.mutation.SetDepth(v)
	return _u
}

// SetNillableDepth sets the "depth" field if the given value is not nil.
func (_u *TemplateFolderUpdateOne) SetNillableDepth(v *int) *TemplateFolderUpdateOne {
	if v != nil {
		_u.SetDepth(*v)
	}
	return _u
}

// AddDepth adds value to the "depth" field.
func (_u *TemplateFolderUpdateOne) AddDepth(v int) *TemplateFolderUpdateOne {
	_u.mutation.AddDepth(v)
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *TemplateFolderUpdateOne) SetSortOrder(v int) *TemplateFolderUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *TemplateFolderUpdateOne) SetNillableSortOrder(v *int) *TemplateFolderUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *TemplateFolderUpdateOne) AddSortOrder(v int) *TemplateFolderUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// AddTemplateIDs adds the "templates" edge to the Template entity by IDs.
func (_u *TemplateFolderUpdateOne) AddTemplateIDs(ids ...string) *TemplateFolderUpdateOne {
	_u.mutation.AddTemplateIDs(ids...)
	return _u
}

// AddTemplates adds the "templates" edges to the Template entity.
func (_u *TemplateFolderUpdateOne) AddTemplates(v ...*Template) *TemplateFolderUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTemplateIDs(ids...)
}

// SetParent sets the "parent" edge to the TemplateFolder entity.
func (_u *TemplateFolderUpdateOne) SetParent(v *TemplateFolder) *TemplateFolderUpdateOne {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the TemplateFolder entity by IDs.
func (_u *TemplateFolderUpdateOne) AddChildIDs(ids ...string) *TemplateFolderUpdateOne {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the TemplateFolder entity.
func (_u *TemplateFolderUpdateOne) AddChildren(v ...*TemplateFolder) *TemplateFolderUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// Mutation returns the TemplateFolderMutation object of the builder.
func (_u *TemplateFolderUpdateOne) Mutation() *TemplateFolderMutation {
	return _u.mutation
}

// ClearTemplates clears all "templates" edges to the Template entity.
func (_u *TemplateFolderUpdateOne) ClearTemplates() *TemplateFolderUpdateOne {
	_u.mutation.ClearTemplates()
	return _u
}

// RemoveTemplateIDs removes the "templates" edge to Template entities by IDs.
func (_u *TemplateFolderUpdateOne) RemoveTemplateIDs(ids ...string) *TemplateFolderUpdateOne {
	_u.mutation.RemoveTemplateIDs(ids...)
	return _u
}

// RemoveTemplates removes "templates" edges to Template entities.
func (_u *TemplateFolderUpdateOne) RemoveTemplates(v ...*Template) *TemplateFolderUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTemplateIDs(ids...)
}

// ClearParent clears the "parent" edge to the TemplateFolder entity.
func (_u *TemplateFolderUpdateOne) ClearParent() *TemplateFolderUpdateOne {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the TemplateFolder entity.
func (_u *TemplateFolderUpdateOne) ClearChildren() *TemplateFolderUpdateOne {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to TemplateFolder entities by IDs.
func (_u *TemplateFolderUpdateOne) RemoveChildIDs(ids ...string) *TemplateFolderUpdateOne {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to TemplateFolder entities.
func (_u *TemplateFolderUpdateOne) RemoveChildren(v ...*TemplateFolder) *TemplateFolderUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// Where appends a list predicates to the TemplateFolderUpdate builder.
func (_u *TemplateFolderUpdateOne) Where(ps ...predicate.TemplateFolder) *TemplateFolderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TemplateFolderUpdateOne) Select(field string, fields ...string) *TemplateFolderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TemplateFolder entity.
func (_u *TemplateFolderUpdateOne) Save(ctx context.Context) (*TemplateFolder, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TemplateFolderUpdateOne) SaveX(ctx context.Context) *TemplateFolder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TemplateFolderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TemplateFolderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TemplateFolderUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := templatefolder.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TemplateFolder.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := templatefolder.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "TemplateFolder.path": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TemplateFolderUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TemplateFolderUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TemplateFolderUpdateOne) sqlSave(ctx context.Context) (_node *TemplateFolder, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(templatefolder.Table, templatefolder.Columns, sqlgraph.NewFieldSpec(templatefolder.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TemplateFolder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, templatefolder.FieldID)
		for _, f := range fields {
			if !templatefolder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != templatefolder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(templatefolder.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(templatefolder.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(templatefolder.FieldCreateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(templatefolder.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(templatefolder.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(templatefolder.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(templatefolder.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(templatefolder.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(templatefolder.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(templatefolder.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(templatefolder.FieldPath, field.TypeString, value)
	}
	if _u.mutation.PathCleared() {
		_spec.ClearField(templatefolder.FieldPath, field.TypeString)
	}
	if value, ok := _u.mutation.Depth(); ok {
		_spec.SetField(templatefolder.FieldDepth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDepth(); ok {
		_spec.AddField(templatefolder.FieldDepth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(templatefolder.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(templatefolder.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.TemplatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   templatefolder.TemplatesTable,
			Columns: []string{templatefolder.TemplatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(template.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTemplatesIDs(); len(nodes) > 0 && !_u.mutation.TemplatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   templatefolder.TemplatesTable,
			Columns: []string{templatefolder.TemplatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(template.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TemplatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   templatefolder.TemplatesTable,
			Columns: []string{templatefolder.TemplatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(template.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   templatefolder.ParentTable,
			Columns: []string{templatefolder.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(templatefolder.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   templatefolder.ParentTable,
			Columns: []string{templatefolder.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(templatefolder.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   templatefolder.ChildrenTable,
			Columns: []string{templatefolder.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(templatefolder.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   templatefolder.ChildrenTable,
			Columns: []string{templatefolder.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(templatefolder.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   templatefolder.ChildrenTable,
			Columns: []string{templatefolder.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(templatefolder.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &TemplateFolder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{templatefolder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
