// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-signing/internal/data/ent/predicate"
	"github.com/go-tangra/go-tangra-signing/internal/data/ent/templatefolder"
)

// TemplateFolderDelete is the builder for deleting a TemplateFolder entity.
type TemplateFolderDelete struct {
	config
	hooks    []Hook
	mutation *TemplateFolderMutation
}

// Where appends a list predicates to the TemplateFolderDelete builder.
func (_d *TemplateFolderDelete) Where(ps ...predicate.TemplateFolder) *TemplateFolderDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TemplateFolderDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TemplateFolderDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TemplateFolderDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(templatefolder.Table, sqlgraph.NewFieldSpec(templatefolder.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TemplateFolderDeleteOne is the builder for deleting a single TemplateFolder entity.
type TemplateFolderDeleteOne struct {
	_d *TemplateFolderDelete
}

// Where appends a list predicates to the TemplateFolderDelete builder.
func (_d *TemplateFolderDeleteOne) Where(ps ...predicate.TemplateFolder) *TemplateFolderDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TemplateFolderDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{templatefolder.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TemplateFolderDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
